# Generated by Django 5.2.6 on 2025-09-24 04:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('finance', 'Finance Management'), ('hr', 'Human Resources'), ('inventory', 'Inventory Management'), ('orders', 'Order Management'), ('analytics', 'Analytics & Reporting'), ('crm', 'Customer Relationship Management'), ('procurement', 'Procurement'), ('manufacturing', 'Manufacturing'), ('quality', 'Quality Management'), ('maintenance', 'Maintenance')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('features', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_prefix', models.CharField(help_text='Unique prefix for auto-generated codes (e.g., ACME, TECH)', max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('detailed_info_submitted', models.BooleanField(default=False)),
                ('detailed_info_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('website', models.URLField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('gst_number', models.CharField(blank=True, help_text='GST Registration Number', max_length=15)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('contact_person_name', models.CharField(blank=True, max_length=255)),
                ('contact_person_title', models.CharField(blank=True, max_length=100)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254)),
                ('contact_person_phone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_companies', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_login_completed', models.BooleanField(default=False)),
                ('first_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('login_attempts', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('password_expires_at', models.DateTimeField()),
                ('must_change_password', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authentication.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_company_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MasterAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('recovery_codes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('login_attempts', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('password_expires_at', models.DateTimeField()),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_secret', models.CharField(blank=True, max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGED', 'Password Changed'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('MASTER_ADMIN_CREATED', 'Master Admin Created'), ('COMPANY_CREATED', 'Company Created'), ('COMPANY_APPROVED', 'Company Approved'), ('COMPANY_DELETED', 'Company Deleted'), ('SERVICE_ASSIGNED', 'Service Assigned'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('DATA_EXPORT', 'Data Export'), ('SETTINGS_CHANGED', 'Settings Changed')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CompanyServiceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Service Admin'), ('manager', 'Service Manager'), ('user', 'Service User'), ('viewer', 'Service Viewer')], default='user', max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.IntegerField(default=0)),
                ('password_expires_at', models.DateTimeField()),
                ('password_changed_at', models.DateTimeField(auto_now_add=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_users', to='authentication.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_service_users', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_users', to='authentication.service')),
            ],
            options={
                'verbose_name': 'Company Service User',
                'verbose_name_plural': 'Company Service Users',
                'unique_together': {('company', 'service', 'username')},
            },
        ),
        migrations.CreateModel(
            name='ServiceUserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='authentication.companyserviceuser')),
            ],
            options={
                'verbose_name': 'Service User Session',
                'verbose_name_plural': 'Service User Sessions',
            },
        ),
        migrations.CreateModel(
            name='CompanyAutoCodeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(choices=[('employee', 'Employee ID'), ('product', 'Product Code'), ('invoice', 'Invoice Number'), ('purchase_order', 'Purchase Order'), ('quotation', 'Quotation Number'), ('customer', 'Customer ID'), ('vendor', 'Vendor ID'), ('asset', 'Asset Code')], max_length=20)),
                ('current_number', models.IntegerField(default=0)),
                ('number_length', models.IntegerField(default=3, help_text='Number of digits (e.g., 3 for 001)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_code_settings', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Company Auto Code Setting',
                'verbose_name_plural': 'Company Auto Code Settings',
                'unique_together': {('company', 'code_type')},
            },
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_password', models.CharField(max_length=128)),
                ('password_changed_at', models.DateTimeField(auto_now_add=True)),
                ('password_expires_at', models.DateTimeField()),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_services', to='authentication.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.service')),
            ],
            options={
                'unique_together': {('company', 'service')},
            },
        ),
    ]
