# Generated by Django 5.2.6 on 2025-09-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN Card Number', max_length=10),
        ),
    ]
