# Generated by Django 5.2.6 on 2025-09-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGED', 'Password Changed'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('MASTER_ADMIN_CREATED', 'Master Admin Created'), ('COMPANY_CREATED', 'Company Created'), ('COMPANY_APPROVED', 'Company Approved'), ('COMPANY_DELETED', 'Company Deleted'), ('SERVICE_ASSIGNED', 'Service Assigned'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('DATA_EXPORT', 'Data Export'), ('SETTINGS_CHANGED', 'Settings Changed')], max_length=30),
        ),
    ]
