# Generated by Django 5.2.6 on 2025-09-24 05:51

from django.db import migrations


def add_new_auto_code_settings(apps, schema_editor):
    """Add proforma_invoice and payment auto-code settings for existing companies"""
    Company = apps.get_model('authentication', 'Company')
    CompanyAutoCodeSettings = apps.get_model('authentication', 'CompanyAutoCodeSettings')
    
    new_code_types = ['proforma_invoice', 'payment']
    
    for company in Company.objects.all():
        for code_type in new_code_types:
            CompanyAutoCodeSettings.objects.get_or_create(
                company=company,
                code_type=code_type,
                defaults={
                    'current_number': 0,
                    'number_length': 3,
                    'is_active': True
                }
            )


def reverse_add_new_auto_code_settings(apps, schema_editor):
    """Remove the new auto-code settings"""
    CompanyAutoCodeSettings = apps.get_model('authentication', 'CompanyAutoCodeSettings')
    CompanyAutoCodeSettings.objects.filter(
        code_type__in=['proforma_invoice', 'payment']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_new_auto_code_settings,
            reverse_add_new_auto_code_settings
        ),
    ]
