# Generated by Django 5.2.6 on 2025-09-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_securitylog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST Registration Number', max_length=15),
        ),
    ]
