# Generated by Django 5.2.6 on 2025-10-09 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_companyuser_password_reset_by_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=200)),
                ('browser', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_trusted', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('master_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_fingerprints', to='authentication.masteradmin')),
            ],
            options={
                'db_table': 'auth_device_fingerprints',
            },
        ),
        migrations.CreateModel(
            name='LoginNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('device_info', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('master_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_notifications', to='authentication.masteradmin')),
            ],
            options={
                'db_table': 'auth_login_notifications',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_restrictions_enabled', models.BooleanField(default=False)),
                ('device_fingerprinting_enabled', models.BooleanField(default=True)),
                ('login_notifications_enabled', models.BooleanField(default=True)),
                ('captcha_after_failed_attempts', models.IntegerField(default=3)),
                ('max_failed_attempts', models.IntegerField(default=5)),
                ('lockout_duration_minutes', models.IntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to='authentication.masteradmin')),
            ],
            options={
                'db_table': 'auth_security_settings',
            },
        ),
        migrations.CreateModel(
            name='IPRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('master_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_restrictions', to='authentication.masteradmin')),
            ],
            options={
                'db_table': 'auth_ip_restrictions',
                'unique_together': {('master_admin', 'ip_address')},
            },
        ),
    ]
