# Generated by Django 5.2.6 on 2025-10-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_devicefingerprint_loginnotification_securitysettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
