# Generated by Django 5.2.6 on 2025-10-13 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_securitysettings_notification_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAdminEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook/Hotmail'), ('yahoo', 'Yahoo Mail'), ('hostinger', 'Hostinger'), ('godaddy', 'GoDaddy'), ('custom', 'Custom SMTP')], default='gmail', max_length=20)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('email_address', models.EmailField(max_length=254)),
                ('email_password', models.CharField(max_length=255)),
                ('from_name', models.CharField(default='SAP System Security', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('emails_sent_today', models.IntegerField(default=0)),
                ('total_emails_sent', models.IntegerField(default=0)),
                ('last_email_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='authentication.masteradmin')),
            ],
            options={
                'verbose_name': 'Master Admin Email Settings',
                'verbose_name_plural': 'Master Admin Email Settings',
                'db_table': 'master_admin_email_settings',
            },
        ),
    ]
