# Generated by Django 5.2.6 on 2025-10-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_populate_unique_service_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyserviceuser',
            name='unique_service_id',
            field=models.CharField(help_text='Unique ID format: COMPANY_username_001', max_length=200, unique=True),
        ),
    ]
