# Generated by Django 5.2.6 on 2025-11-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_make_unique_service_id_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='use_document_numbering',
            field=models.BooleanField(default=False, help_text='Enable centralized document numbering system'),
        ),
    ]
