# Generated by Django 5.2.9 on 2026-01-31 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_fix_session_fields'),
        ('authentication', '0012_company_use_document_numbering'),
    ]

    operations = [
    ]
