# Generated by Django 5.2.6 on 2026-01-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_merge_20260131_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RunSQL(
            "INSERT INTO authentication_service (name, service_type, description, is_active, base_price, features, created_at, updated_at) VALUES ('Athens Sustainability', 'athens_sustainability', 'Comprehensive sustainability management platform for ESG, environmental compliance, and green finance', true, 999.00, '[\"ESG Reporting\", \"Environmental Compliance\", \"Carbon Footprint Tracking\", \"Energy Management\", \"Waste Management\", \"Water Usage Monitoring\", \"Sustainability Metrics\", \"Green Finance Tools\", \"Compliance Dashboard\", \"Automated Reporting\"]', NOW(), NOW()) ON CONFLICT (service_type) DO NOTHING;",
            reverse_sql="DELETE FROM authentication_service WHERE service_type = 'athens_sustainability';"
        ),
    ]