# Generated by Django 5.2.9 on 2026-02-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_auto_20260131_1606"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securitylog",
            name="event_type",
            field=models.CharField(
                max_length=50,
                choices=[
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("ACCOUNT_LOCKED", "Account Locked"),
                    ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                    ("MASTER_ADMIN_CREATED", "Master Admin Created"),
                    ("COMPANY_CREATED", "Company Created"),
                    ("COMPANY_APPROVED", "Company Approved"),
                    ("COMPANY_DELETED", "Company Deleted"),
                    ("SERVICE_ASSIGNED", "Service Assigned"),
                    ("USER_DELETED", "Service User Deleted"),
                    ("UNAUTHORIZED_ACCESS", "Unauthorized Access"),
                    ("DATA_EXPORT", "Data Export"),
                    ("SETTINGS_CHANGED", "Settings Changed"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                max_length=30,
                unique=True,
                choices=[
                    ("finance", "Finance Management"),
                    ("hr", "Human Resources"),
                    ("inventory", "Inventory Management"),
                    ("orders", "Order Management"),
                    ("analytics", "Analytics & Reporting"),
                    ("crm", "Customer Relationship Management"),
                    ("athens_sustainability", "Athens Sustainability"),
                    ("procurement", "Procurement"),
                    ("manufacturing", "Manufacturing"),
                    ("quality", "Quality Management"),
                    ("maintenance", "Maintenance"),
                ],
            ),
        ),
    ]
