# Generated by Django 5.2.9 on 2026-02-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_service_service_type'),
        ('authentication', '0017_increase_service_type_length'),
    ]

    operations = [
    ]
