# Generated by Django 5.2.9 on 2026-02-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_athens_user_workflow_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='profile_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_started', max_length=30),
        ),
    ]
