# Generated by Django 5.2.9 on 2026-04-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_remove_invoice_status_update_po_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_account_holder',
            field=models.CharField(blank=True, help_text='Account holder name (if different from company name)', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_type',
            field=models.CharField(blank=True, default='Current', help_text='Account type e.g. Current, Savings', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_branch',
            field=models.CharField(blank=True, help_text='Bank branch name', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, help_text='IFSC code', max_length=11),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for payment details on documents', max_length=100),
        ),
    ]
