# Generated by Django 5.2.9 on 2026-07-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermitToWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(blank=True, max_length=100)),
                ('permit_type', models.CharField(choices=[('hot_work', 'Hot Work'), ('cold_work', 'Cold Work'), ('confined_space', 'Confined Space Entry'), ('electrical', 'Electrical Work'), ('height', 'Work at Height'), ('excavation', 'Excavation'), ('chemical', 'Chemical Handling'), ('general', 'General Work'), ('other', 'Other')], default='general', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('work_location', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('contractor_name', models.CharField(blank=True, max_length=255)),
                ('work_description', models.TextField(blank=True)),
                ('risk_assessment_details', models.TextField(blank=True)),
                ('ppe_requirements', models.TextField(blank=True)),
                ('safety_precautions', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=255)),
                ('issuer_name', models.CharField(blank=True, max_length=255)),
                ('authorized_signatures', models.TextField(blank=True)),
                ('source_image', models.ImageField(blank=True, null=True, upload_to='ptw_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
