#!/bin/bash

# Quick Start Guide - Email Templates Testing
# ============================================

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         SAP Email Templates - Quick Start Guide               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📧 Email Templates Setup Complete!${NC}"
echo ""
echo "Three email templates have been created:"
echo "  1. Invoice Email (Purple gradient)"
echo "  2. Quotation Email (Pink gradient)"
echo "  3. Receipt Email (Green gradient)"
echo ""

echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}OPTION 1: Interactive Test Script (Recommended)${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Run the interactive test script:"
echo ""
echo "  cd /var/www/SAP-Python/backend"
echo "  ./test_email_config.sh"
echo ""

echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}OPTION 2: Command Line Testing${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Test simple email:"
echo "  sudo -u www-data bash -c 'cd /var/www/SAP-Python/backend && source venv/bin/activate && python manage.py test_email --type=simple --to=YOUR_EMAIL@example.com'"
echo ""
echo "Test invoice email (Invoice ID: 225):"
echo "  sudo -u www-data bash -c 'cd /var/www/SAP-Python/backend && source venv/bin/activate && python manage.py test_email --type=invoice --to=YOUR_EMAIL@example.com --id=225'"
echo ""
echo "Test quotation email (Quotation ID: 71):"
echo "  sudo -u www-data bash -c 'cd /var/www/SAP-Python/backend && source venv/bin/activate && python manage.py test_email --type=quotation --to=YOUR_EMAIL@example.com --id=71'"
echo ""

echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}OPTION 3: Use in Python Code${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "from finance.email_service import FinanceEmailService"
echo ""
echo "# Send invoice email"
echo "invoice = Invoice.objects.get(id=225)"
echo "FinanceEmailService.send_invoice_email(invoice, 'customer@example.com')"
echo ""
echo "# Send quotation email"
echo "quotation = Quotation.objects.get(id=71)"
echo "FinanceEmailService.send_quotation_email(quotation, 'customer@example.com')"
echo ""

echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}📋 Sample Data Available${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Invoices:"
echo "  ID: 225 - BKGE-INV-2026-27-001 - ₹1,124,894.00"
echo "  ID: 224 - BKC/055/2526 - ₹556,263.80"
echo "  ID: 223 - BKC/039/2526 - ₹2,360,000.00"
echo ""
echo "Quotations:"
echo "  ID: 71 - SE-QT-2627-001 - ₹67,160.29"
echo "  ID: 70 - TC-QT-2025-26-007 - ₹435,420.00"
echo "  ID: 69 - TC-QT-2025-26-006 - ₹14,726.40"
echo ""

echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}⚙️  Email Configuration${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Current email settings (from .env):"
echo "  SMTP Host: smtp.hostinger.com"
echo "  SMTP Port: 587"
echo "  Use TLS: True"
echo ""
echo "⚠️  Make sure to update EMAIL_HOST_USER and EMAIL_HOST_PASSWORD in .env"
echo ""

echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}📚 Documentation${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Full documentation:"
echo "  /var/www/SAP-Python/backend/EMAIL_SETUP_SUMMARY.md"
echo "  /var/www/SAP-Python/backend/finance/templates/email/README.md"
echo ""

echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Files Created${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "✓ finance/templates/email/invoice_email.html"
echo "✓ finance/templates/email/quotation_email.html"
echo "✓ finance/templates/email/receipt_email.html"
echo "✓ finance/email_service.py"
echo "✓ finance/management/commands/test_email.py"
echo "✓ test_email_config.sh"
echo "✓ EMAIL_SETUP_SUMMARY.md"
echo ""

echo -e "${GREEN}🚀 Ready to test! Choose an option above to get started.${NC}"
echo ""
