# Generated by Django 5.2.6 on 2025-10-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_pan_number_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain_name',
            field=models.CharField(blank=True, help_text='Company domain (e.g., athenas.co.in)', max_length=255),
        ),
    ]
