# Generated by Django 5.2.6 on 2025-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_company_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='password_reset_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
