# Generated by Django 5.2.6 on 2025-10-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_companyuser_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitysettings',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Email to receive login notifications', max_length=254, null=True),
        ),
    ]
