# Generated by Django 5.2.6 on 2025-10-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_masteradminemailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyserviceuser',
            name='unique_service_id',
            field=models.CharField(blank=True, help_text='Unique ID format: COMPANY_username_001', max_length=200, null=True, unique=True),
        ),
    ]
