# Generated by Django 5.2.9 on 2026-02-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_securitylog_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('finance', 'Finance Management'), ('hr', 'Human Resources'), ('inventory', 'Inventory Management'), ('orders', 'Order Management'), ('analytics', 'Analytics & Reporting'), ('crm', 'Customer Relationship Management'), ('athens_sustainability', 'Athens Sustainability'), ('procurement', 'Procurement'), ('manufacturing', 'Manufacturing'), ('quality', 'Quality Management'), ('maintenance', 'Maintenance')], max_length=30, unique=True),
        ),
    ]
