from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def backfill_user_workflow(apps, schema_editor):
    CompanyUser = apps.get_model('authentication', 'CompanyUser')
    now = timezone.now()

    CompanyUser.objects.all().update(
        profile_status='approved',
        profile_submitted_at=now,
        profile_approved_at=now,
        has_completed_induction=True,
        is_password_reset_required=False,
        is_autogenerated_password=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_merge_20260201_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='grade',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='is_password_reset_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='is_autogenerated_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='profile_status',
            field=models.CharField(
                choices=[
                    ('not_started', 'Not Started'),
                    ('draft', 'Draft'),
                    ('submitted', 'Submitted'),
                    ('changes_requested', 'Changes Requested'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected'),
                ],
                default='not_started',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='profile_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='profile_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='profile_approved_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='approved_user_profiles',
                to='authentication.companyuser',
            ),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='profile_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='has_completed_induction',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_user_workflow, migrations.RunPython.noop),
    ]
