# Generated by Django 5.2.9 on 2026-02-03 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athens_sustainability', '0006_alter_athensprojectadmin_unique_together_and_more'),
        ('authentication', '0020_alter_companyuser_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='induction_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_users', to='athens_sustainability.athenssustproject'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('epc', 'EPC'), ('contractor', 'Contractor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='is_autogenerated_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='is_password_reset_required',
            field=models.BooleanField(default=True),
        ),
    ]
