# Generated by Django 5.2.6 on 2025-10-08 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_companyuser_password_reset_by_admin'),
        ('hr', '0005_add_leave_banking_esi_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_face_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_faces/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_face_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_faces/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='face_match_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_valid_face_match',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancesystem',
            name='enable_face_recognition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesystem',
            name='face_match_threshold',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=3),
        ),
        migrations.AddField(
            model_name='attendancesystem',
            name='require_face_for_checkin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesystem',
            name='require_face_for_checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='engagement_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Employee engagement score', max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_encoding',
            field=models.JSONField(blank=True, default=list, help_text='Face encoding data for recognition'),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_photo',
            field=models.ImageField(blank=True, help_text='Photo for face recognition attendance', null=True, upload_to='employee_faces/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='performance_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='AI-calculated performance score', max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='retention_risk',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text='AI-predicted retention risk', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ai_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='AI-calculated candidate score', max_digits=5),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ai_screening_notes',
            field=models.TextField(blank=True, help_text='AI-generated screening notes'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skill_match_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Skills matching percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='ai_screening_enabled',
            field=models.BooleanField(default=True, help_text='Enable AI-powered candidate screening'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='ai_performance_prediction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='AI-predicted future performance', max_digits=5),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='improvement_suggestions',
            field=models.JSONField(default=list, help_text='AI-generated improvement suggestions'),
        ),
        migrations.CreateModel(
            name='ChallanGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(max_length=50, unique=True)),
                ('challan_type', models.CharField(choices=[('pf', 'PF Challan'), ('esi', 'ESI Challan'), ('pt', 'Professional Tax Challan'), ('tds', 'TDS Challan')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField()),
                ('bank_details', models.JSONField(default=dict)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('challan_file_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='authentication.company')),
                ('government_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='hr.governmentreturn')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epfo_username', models.CharField(blank=True, max_length=100)),
                ('epfo_password', models.CharField(blank=True, max_length=255)),
                ('epfo_digital_signature', models.TextField(blank=True)),
                ('esic_username', models.CharField(blank=True, max_length=100)),
                ('esic_password', models.CharField(blank=True, max_length=255)),
                ('esic_digital_signature', models.TextField(blank=True)),
                ('it_username', models.CharField(blank=True, max_length=100)),
                ('it_password', models.CharField(blank=True, max_length=255)),
                ('it_digital_signature', models.TextField(blank=True)),
                ('pt_username', models.CharField(blank=True, max_length=100)),
                ('pt_password', models.CharField(blank=True, max_length=255)),
                ('epfo_api_key', models.CharField(blank=True, max_length=255)),
                ('esic_api_key', models.CharField(blank=True, max_length=255)),
                ('it_api_key', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_credentials', to='authentication.company')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_name', models.CharField(max_length=50)),
                ('submission_method', models.CharField(choices=[('api', 'API'), ('manual', 'Manual Upload'), ('bulk', 'Bulk Upload')], default='api', max_length=20)),
                ('acknowledgment_number', models.CharField(blank=True, max_length=100)),
                ('submission_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('error', 'Error')], default='pending', max_length=20)),
                ('response_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_logs', to='authentication.company')),
                ('government_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_logs', to='hr.governmentreturn')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companyserviceuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
