# Generated by Django 5.2.6 on 2025-10-08 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_companyuser_password_reset_by_admin'),
        ('hr', '0005_add_leave_banking_esi_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallanGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(max_length=50, unique=True)),
                ('challan_type', models.CharField(choices=[('pf', 'PF Challan'), ('esi', 'ESI Challan'), ('pt', 'Professional Tax Challan'), ('tds', 'TDS Challan')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField()),
                ('bank_details', models.JSONField(default=dict)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('challan_file_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='authentication.company')),
                ('government_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='hr.governmentreturn')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epfo_username', models.CharField(blank=True, max_length=100)),
                ('epfo_password', models.CharField(blank=True, max_length=255)),
                ('epfo_digital_signature', models.TextField(blank=True)),
                ('esic_username', models.CharField(blank=True, max_length=100)),
                ('esic_password', models.CharField(blank=True, max_length=255)),
                ('esic_digital_signature', models.TextField(blank=True)),
                ('it_username', models.CharField(blank=True, max_length=100)),
                ('it_password', models.CharField(blank=True, max_length=255)),
                ('it_digital_signature', models.TextField(blank=True)),
                ('pt_username', models.CharField(blank=True, max_length=100)),
                ('pt_password', models.CharField(blank=True, max_length=255)),
                ('epfo_api_key', models.CharField(blank=True, max_length=255)),
                ('esic_api_key', models.CharField(blank=True, max_length=255)),
                ('it_api_key', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_credentials', to='authentication.company')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_name', models.CharField(max_length=50)),
                ('submission_method', models.CharField(choices=[('api', 'API'), ('manual', 'Manual Upload'), ('bulk', 'Bulk Upload')], default='api', max_length=20)),
                ('acknowledgment_number', models.CharField(blank=True, max_length=100)),
                ('submission_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('error', 'Error')], default='pending', max_length=20)),
                ('response_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_logs', to='authentication.company')),
                ('government_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_logs', to='hr.governmentreturn')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companyserviceuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
