# Generated by Django 5.2.6 on 2025-10-23 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_make_unique_service_id_required'),
        ('hr', '0010_leavetype_carry_forward'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkShareOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platforms', models.JSONField(default=list)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_shares', models.IntegerField(default=0)),
                ('successful_shares', models.IntegerField(default=0)),
                ('failed_shares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_shares', to='authentication.company')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companyserviceuser')),
                ('job_postings', models.ManyToManyField(related_name='bulk_shares', to='hr.jobposting')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobShareAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('gmail', 'Gmail'), ('outlook', 'Outlook'), ('email', 'Other Email'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('copy_link', 'Copy Link')], max_length=20)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('utm_source', models.CharField(blank=True, max_length=50)),
                ('utm_medium', models.CharField(default='social', max_length=50)),
                ('utm_campaign', models.CharField(default='job_sharing', max_length=100)),
                ('clicks_from_share', models.IntegerField(default=0)),
                ('applications_from_share', models.IntegerField(default=0)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_analytics', to='hr.jobposting')),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companyserviceuser')),
            ],
            options={
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('creative', 'Creative'), ('urgent', 'Urgent'), ('remote', 'Remote Work'), ('custom', 'Custom')], max_length=20)),
                ('template_content', models.TextField()),
                ('whatsapp_template', models.TextField(blank=True)),
                ('linkedin_template', models.TextField(blank=True)),
                ('facebook_template', models.TextField(blank=True)),
                ('twitter_template', models.TextField(blank=True)),
                ('instagram_template', models.TextField(blank=True)),
                ('email_template', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companyserviceuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_platforms', models.JSONField(default=list)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_campaigns', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companyserviceuser')),
                ('job_postings', models.ManyToManyField(related_name='campaigns', to='hr.jobposting')),
                ('message_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.messagetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareClickTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True)),
                ('share_analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='hr.jobshareanalytics')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='SharePerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('gmail', 'Gmail'), ('outlook', 'Outlook'), ('email', 'Other Email'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('copy_link', 'Copy Link')], max_length=20)),
                ('date', models.DateField()),
                ('total_shares', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('click_through_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_metrics', to='authentication.company')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='hr.jobposting')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='jobshareanalytics',
            index=models.Index(fields=['job_posting', 'platform'], name='hr_jobshare_job_pos_7cb8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='jobshareanalytics',
            index=models.Index(fields=['shared_at'], name='hr_jobshare_shared__5794c3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobshareanalytics',
            index=models.Index(fields=['shared_by'], name='hr_jobshare_shared__a17287_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='shareperformancemetrics',
            unique_together={('company', 'job_posting', 'platform', 'date')},
        ),
    ]
