# Generated by Django 5.2.6 on 2025-10-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_bulkshareoperation_jobshareanalytics_messagetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='current_company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='current_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='current_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='current_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='education_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notice_period',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='relevant_experience',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='total_experience',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='willing_to_relocate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload resume/CV', upload_to='resumes/'),
        ),
    ]
