# Generated by Django 5.2.6 on 2025-10-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_jobapplication_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='application_source',
            field=models.CharField(choices=[('direct', 'Direct Application'), ('whatsapp', 'WhatsApp Share'), ('linkedin', 'LinkedIn Share'), ('gmail', 'Gmail Share'), ('outlook', 'Outlook Share'), ('facebook', 'Facebook Share'), ('twitter', 'Twitter Share'), ('instagram', 'Instagram Share'), ('telegram', 'Telegram Share'), ('other_email', 'Other Email Share'), ('copy_link', 'Copy Link Share')], default='direct', help_text='Source platform from which application was submitted', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='share_id',
            field=models.CharField(blank=True, help_text='Share tracking ID if from social media', max_length=100),
        ),
    ]
