# Generated by Django 5.2.6 on 2025-10-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_add_application_source_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether invitation email was sent'),
        ),
        migrations.AddField(
            model_name='interview',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When invitation email was sent', null=True),
        ),
    ]
