# Generated by Django 5.2.6 on 2025-10-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_make_unique_service_id_required'),
        ('hr', '0014_add_interview_email_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='designation',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'is_active'], name='hr_departme_company_cb89ba_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'code'], name='hr_departme_company_aa520a_idx'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['company', 'is_active'], name='hr_designat_company_b839e9_idx'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['company', 'code'], name='hr_designat_company_4f3e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['department', 'is_active'], name='hr_designat_departm_ad6614_idx'),
        ),
    ]
