# Generated by Django 5.2.6 on 2025-11-04 05:22

import hr.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_update_department_designation_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=hr.models.FlexibleJSONField(blank=True, default=list, help_text='List of employee skills'),
        ),
    ]
