# Generated by Django 5.2.6 on 2025-11-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_remove_ai_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_face_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_faces/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_face_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_faces/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='face_match_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_valid_face_match',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancesystem',
            name='enable_face_recognition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesystem',
            name='face_match_threshold',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=3),
        ),
        migrations.AddField(
            model_name='attendancesystem',
            name='require_face_for_checkin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesystem',
            name='require_face_for_checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='engagement_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Employee engagement score', max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_encoding',
            field=models.JSONField(blank=True, default=list, help_text='Face encoding data for recognition'),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_photo',
            field=models.ImageField(blank=True, help_text='Photo for face recognition attendance', null=True, upload_to='employee_faces/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='performance_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='AI-calculated performance score', max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='retention_risk',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text='AI-predicted retention risk', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ai_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='AI-calculated candidate score', max_digits=5),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ai_screening_notes',
            field=models.TextField(blank=True, help_text='AI-generated screening notes'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skill_match_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Skills matching percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='ai_screening_enabled',
            field=models.BooleanField(default=True, help_text='Enable AI-powered candidate screening'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='ai_performance_prediction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='AI-predicted future performance', max_digits=5),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='improvement_suggestions',
            field=models.JSONField(default=list, help_text='AI-generated improvement suggestions'),
        ),
        migrations.AlterField(
            model_name='portalcredentials',
            name='epfo_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='portalcredentials',
            name='esic_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='portalcredentials',
            name='it_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='portalcredentials',
            name='pt_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
