# Generated by Django 5.2.6 on 2025-11-21 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_company_use_document_numbering'),
        ('hr', '0019_add_back_ai_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceFormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_type', models.CharField(choices=[('register_of_fines', 'Register of Fines'), ('register_of_workmen', 'Register of Workmen')], max_length=50)),
                ('template_name', models.CharField(max_length=200)),
                ('is_monthly_auto_generate', models.BooleanField(default=True)),
                ('generation_day', models.IntegerField(default=1, help_text='Day of month to generate (1-28)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to='authentication.company')),
            ],
            options={
                'unique_together': {('company', 'form_type')},
            },
        ),
        migrations.CreateModel(
            name='FormGenerationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateTimeField()),
                ('is_executed', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_schedules', to='authentication.company')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.complianceformtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyComplianceForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('in_review', 'In Review'), ('approved', 'Approved'), ('submitted', 'Submitted to Authority')], default='generated', max_length=20)),
                ('total_employees', models.IntegerField(default=0)),
                ('auto_generated', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companyserviceuser')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_forms', to='authentication.company')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.complianceformtemplate')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('company', 'template', 'month')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeFormEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fine_reason', models.TextField(blank=True)),
                ('fine_date', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('basic_wage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('monthly_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_entries', to='hr.monthlycomplianceform')),
            ],
            options={
                'unique_together': {('monthly_form', 'employee')},
            },
        ),
    ]
