# Generated by Django 5.2.6 on 2025-11-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_complianceformtemplate_formgenerationschedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complianceformtemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='complianceformtemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='complianceformtemplate',
            name='file_type',
            field=models.CharField(blank=True, choices=[('excel', 'Excel'), ('pdf', 'PDF')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='complianceformtemplate',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='compliance_templates/'),
        ),
        migrations.AlterField(
            model_name='complianceformtemplate',
            name='form_type',
            field=models.CharField(choices=[('register_of_fines', 'Register of Fines'), ('register_of_workmen', 'Register of Workmen'), ('custom_template', 'Custom Template')], max_length=50),
        ),
    ]
