# Generated by Django 5.2.6 on 2025-11-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_alter_complianceformtemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_remarks',
            field=models.TextField(blank=True, help_text='General remarks about employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_signature',
            field=models.ImageField(blank=True, help_text='Digital signature of employee', null=True, upload_to='employee_signatures/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='father_husband_name',
            field=models.CharField(blank=True, help_text="Father's or Husband's name as per Form XIII", max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='local_address_line1',
            field=models.CharField(blank=True, help_text='Local/current address line 1', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='local_address_line2',
            field=models.CharField(blank=True, help_text='Local/current address line 2', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='local_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='local_country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='local_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='local_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='nature_of_employment',
            field=models.CharField(blank=True, help_text='Nature of employment/work description', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address_line1',
            field=models.CharField(blank=True, help_text='Permanent address line 1', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address_line2',
            field=models.CharField(blank=True, help_text='Permanent address line 2', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_reason',
            field=models.TextField(blank=True, help_text='Reason for termination if applicable'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address_line1',
            field=models.CharField(blank=True, help_text='Deprecated: Use permanent_address_line1', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Deprecated: Use permanent_address_line2', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, help_text='Deprecated: Use permanent_city', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(default='India', help_text='Deprecated: Use permanent_country', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pincode',
            field=models.CharField(blank=True, help_text='Deprecated: Use permanent_pincode', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, help_text='Deprecated: Use permanent_state', max_length=100),
        ),
    ]
