# Generated by Django 5.2.6 on 2025-11-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_add_form_xiii_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeformentry',
            name='father_husband_name',
            field=models.CharField(blank=True, help_text="Father's/Husband's name", max_length=200),
        ),
        migrations.AddField(
            model_name='employeeformentry',
            name='local_address',
            field=models.TextField(blank=True, help_text='Local address'),
        ),
        migrations.AddField(
            model_name='employeeformentry',
            name='nature_of_employment',
            field=models.CharField(blank=True, help_text='Nature of employment', max_length=200),
        ),
        migrations.AddField(
            model_name='employeeformentry',
            name='permanent_address',
            field=models.TextField(blank=True, help_text='Permanent address'),
        ),
        migrations.AddField(
            model_name='employeeformentry',
            name='termination_date',
            field=models.DateField(blank=True, help_text='Date of termination', null=True),
        ),
        migrations.AddField(
            model_name='employeeformentry',
            name='termination_reason',
            field=models.TextField(blank=True, help_text='Reason for termination'),
        ),
    ]
