# Generated by Django 5.2.6 on 2025-11-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_update_form_entry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, help_text='Date of termination if applicable', null=True),
        ),
    ]
