# Generated by Django 5.2.6 on 2025-11-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_add_termination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceformtemplate',
            name='file_type',
            field=models.CharField(blank=True, choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('word', 'Word')], max_length=10, null=True),
        ),
    ]
