# Generated by Django 5.2.6 on 2025-11-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_add_word_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceformtemplate',
            name='template_structure',
            field=models.JSONField(blank=True, default=dict, help_text='Parsed template structure and fields'),
        ),
        migrations.AddField(
            model_name='employeeformentry',
            name='dynamic_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic data based on template structure'),
        ),
    ]
