# Generated by Django 5.2.9 on 2026-02-03 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_companyuser_profile_status'),
        ('hr', '0026_add_dynamic_template_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='application',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interviewer',
        ),
        migrations.RemoveField(
            model_name='interviewfeedback',
            name='interview',
        ),
        migrations.RemoveField(
            model_name='interviewscheduletemplate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='application',
        ),
        migrations.RemoveField(
            model_name='jobshareanalytics',
            name='job_posting',
        ),
        migrations.RemoveField(
            model_name='jobshareanalytics',
            name='shared_by',
        ),
        migrations.RemoveField(
            model_name='shareclicktracking',
            name='share_analytics',
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sharecampaign',
            name='message_template',
        ),
        migrations.RemoveField(
            model_name='offertemplate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sharecampaign',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sharecampaign',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sharecampaign',
            name='job_postings',
        ),
        migrations.AlterUniqueTogether(
            name='shareperformancemetrics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shareperformancemetrics',
            name='company',
        ),
        migrations.RemoveField(
            model_name='shareperformancemetrics',
            name='job_posting',
        ),
        migrations.CreateModel(
            name='EmployeeAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
                ('access_granted', models.BooleanField()),
                ('access_level_at_time', models.CharField(max_length=15)),
                ('workflow_stage_at_time', models.CharField(max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfileCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture_uploaded', models.BooleanField(default=False)),
                ('face_photo_uploaded', models.BooleanField(default=False)),
                ('personal_details_completed', models.BooleanField(default=False)),
                ('address_details_completed', models.BooleanField(default=False)),
                ('government_ids_completed', models.BooleanField(default=False)),
                ('banking_details_completed', models.BooleanField(default=False)),
                ('emergency_contact_completed', models.BooleanField(default=False)),
                ('aadhar_document', models.FileField(blank=True, null=True, upload_to='employee_documents/aadhar/')),
                ('pan_document', models.FileField(blank=True, null=True, upload_to='employee_documents/pan/')),
                ('bank_passbook', models.FileField(blank=True, null=True, upload_to='employee_documents/bank/')),
                ('educational_certificates', models.FileField(blank=True, null=True, upload_to='employee_documents/education/')),
                ('experience_certificates', models.FileField(blank=True, null=True, upload_to='employee_documents/experience/')),
                ('completion_percentage', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('submitted_for_approval', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_completion', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeWorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('basic_details_created', 'Basic Details Created'), ('credentials_shared', 'Credentials Shared'), ('password_reset_required', 'Password Reset Required'), ('password_reset_completed', 'Password Reset Completed'), ('profile_completion_required', 'Profile Completion Required'), ('profile_submitted', 'Profile Submitted for Approval'), ('profile_approved', 'Profile Approved'), ('profile_rejected', 'Profile Rejected'), ('induction_required', 'Induction Training Required'), ('induction_in_progress', 'Induction Training In Progress'), ('induction_completed', 'Induction Training Completed'), ('full_access_granted', 'Full Access Granted'), ('access_revoked', 'Access Revoked')], default='basic_details_created', max_length=30)),
                ('access_level', models.CharField(choices=[('none', 'No Access'), ('limited', 'Limited Access - Profile Only'), ('training_only', 'Training Access Only'), ('full', 'Full Access')], default='none', max_length=15)),
                ('basic_details_completed_at', models.DateTimeField(blank=True, null=True)),
                ('credentials_shared_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_at', models.DateTimeField(blank=True, null=True)),
                ('profile_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('profile_approved_at', models.DateTimeField(blank=True, null=True)),
                ('profile_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('induction_started_at', models.DateTimeField(blank=True, null=True)),
                ('induction_completed_at', models.DateTimeField(blank=True, null=True)),
                ('full_access_granted_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('email_notifications_sent', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_employee_profiles', to='authentication.companyserviceuser')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_status', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Employee Workflow Status',
                'verbose_name_plural': 'Employee Workflow Statuses',
            },
        ),
        migrations.CreateModel(
            name='InductionTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='induction_materials/')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('estimated_duration_minutes', models.IntegerField(default=30)),
                ('has_quiz', models.BooleanField(default=False)),
                ('quiz_questions', models.JSONField(blank=True, default=list)),
                ('passing_score', models.IntegerField(default=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='induction_modules', to='authentication.company')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeInductionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('quiz_attempted', models.BooleanField(default=False)),
                ('quiz_score', models.IntegerField(blank=True, null=True)),
                ('quiz_passed', models.BooleanField(default=False)),
                ('quiz_attempts', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='induction_progress', to='hr.employee')),
                ('training_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_progress', to='hr.inductiontraining')),
            ],
            options={
                'unique_together': {('employee', 'training_module')},
            },
        ),
        migrations.DeleteModel(
            name='BulkShareOperation',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='InterviewFeedback',
        ),
        migrations.DeleteModel(
            name='InterviewScheduleTemplate',
        ),
        migrations.DeleteModel(
            name='JobOffer',
        ),
        migrations.DeleteModel(
            name='JobShareAnalytics',
        ),
        migrations.DeleteModel(
            name='ShareClickTracking',
        ),
        migrations.DeleteModel(
            name='MessageTemplate',
        ),
        migrations.DeleteModel(
            name='OfferTemplate',
        ),
        migrations.DeleteModel(
            name='ShareCampaign',
        ),
        migrations.DeleteModel(
            name='SharePerformanceMetrics',
        ),
    ]
