# Generated by Django 5.2.9 on 2026-07-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_remove_interview_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='training_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='application_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='application_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payrollcycle',
            name='payroll_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='review_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='designation',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='esimedicalbenefit',
            name='claim_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
