# Generated by Django 5.2.9 on 2026-07-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_company_bank_account_holder_and_more'),
        ('hr', '0030_employeemobilesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_off_days', models.JSONField(blank=True, default=list, help_text='Python weekdays: Monday=0, Sunday=6')),
                ('full_day_min_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('half_day_min_hours', models.DecimalField(decimal_places=2, default=4.0, max_digits=4)),
                ('overtime_after_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('paid_holiday_payable', models.BooleanField(default=True)),
                ('paid_leave_payable', models.BooleanField(default=True)),
                ('unpaid_leave_deductible', models.BooleanField(default=True)),
                ('exclude_weekoffs_from_leave', models.BooleanField(default=True)),
                ('exclude_holidays_from_leave', models.BooleanField(default=True)),
                ('lock_attendance_after_payroll', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policy', to='authentication.company')),
            ],
        ),
    ]
