# Generated by Django 5.2.9 on 2026-07-16 11:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_company_bank_account_holder_and_more'),
        ('hr', '0034_restore_interview_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='communication_rating',
            field=models.IntegerField(blank=True, help_text='Communication rating (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='interview',
            name='cultural_fit_rating',
            field=models.IntegerField(blank=True, help_text='Cultural fit rating (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_interviews', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='overall_rating',
            field=models.IntegerField(blank=True, help_text='Overall rating (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='interview',
            name='technical_rating',
            field=models.IntegerField(blank=True, help_text='Technical skills rating (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='BulkShareOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platforms', models.JSONField(default=list)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_shares', models.IntegerField(default=0)),
                ('successful_shares', models.IntegerField(default=0)),
                ('failed_shares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_shares', to='authentication.company')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companyserviceuser')),
                ('job_postings', models.ManyToManyField(related_name='bulk_shares', to='hr.jobposting')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_offered', models.DecimalField(decimal_places=2, max_digits=12)),
                ('joining_date', models.DateField()),
                ('offer_valid_until', models.DateField()),
                ('benefits', models.TextField(blank=True, help_text='Benefits and perks')),
                ('terms_conditions', models.TextField(blank=True, help_text='Terms and conditions')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_response', models.TextField(blank=True, help_text="Candidate's response/feedback")),
                ('negotiation_notes', models.TextField(blank=True, help_text='Salary negotiation notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='hr.jobapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobShareAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('gmail', 'Gmail'), ('outlook', 'Outlook'), ('email', 'Other Email'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('copy_link', 'Copy Link')], max_length=20)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('utm_source', models.CharField(blank=True, max_length=50)),
                ('utm_medium', models.CharField(default='social', max_length=50)),
                ('utm_campaign', models.CharField(default='job_sharing', max_length=100)),
                ('clicks_from_share', models.IntegerField(default=0)),
                ('applications_from_share', models.IntegerField(default=0)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_analytics', to='hr.jobposting')),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companyserviceuser')),
            ],
            options={
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('creative', 'Creative'), ('urgent', 'Urgent'), ('remote', 'Remote Work'), ('custom', 'Custom')], max_length=20)),
                ('template_content', models.TextField()),
                ('whatsapp_template', models.TextField(blank=True)),
                ('linkedin_template', models.TextField(blank=True)),
                ('facebook_template', models.TextField(blank=True)),
                ('twitter_template', models.TextField(blank=True)),
                ('instagram_template', models.TextField(blank=True)),
                ('email_template', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companyserviceuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject_template', models.CharField(default='Job Offer - {position} at {company}', max_length=200)),
                ('email_template', models.TextField(help_text='Email template with placeholders')),
                ('default_benefits', models.TextField(blank=True)),
                ('default_terms', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_templates', to='authentication.company')),
            ],
        ),
        migrations.CreateModel(
            name='ShareCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_platforms', models.JSONField(default=list)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_campaigns', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companyserviceuser')),
                ('job_postings', models.ManyToManyField(related_name='campaigns', to='hr.jobposting')),
                ('message_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.messagetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareClickTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True)),
                ('share_analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='hr.jobshareanalytics')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='SharePerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('gmail', 'Gmail'), ('outlook', 'Outlook'), ('email', 'Other Email'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('copy_link', 'Copy Link')], max_length=20)),
                ('date', models.DateField()),
                ('total_shares', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('click_through_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_metrics', to='authentication.company')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='hr.jobposting')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='jobshareanalytics',
            index=models.Index(fields=['job_posting', 'platform'], name='hr_jobshare_job_pos_7cb8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='jobshareanalytics',
            index=models.Index(fields=['shared_at'], name='hr_jobshare_shared__5794c3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobshareanalytics',
            index=models.Index(fields=['shared_by'], name='hr_jobshare_shared__a17287_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='shareperformancemetrics',
            unique_together={('company', 'job_posting', 'platform', 'date')},
        ),
    ]
