# Generated by Django 5.2.9 on 2026-07-17

import django.db.models.deletion
import uuid
from django.db import migrations, models


def populate_offer_response_tokens(apps, schema_editor):
    JobOffer = apps.get_model('hr', 'JobOffer')
    for offer in JobOffer.objects.filter(response_token__isnull=True).iterator():
        offer.response_token = uuid.uuid4()
        offer.save(update_fields=['response_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_company_bank_account_holder_and_more'),
        ('hr', '0035_alter_interview_communication_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='response_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(
            populate_offer_response_tokens,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='response_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='response_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='response_user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_job_applications', to='authentication.companyserviceuser'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='converted_employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_job_application', to='hr.employee'),
        ),
    ]
