# Generated by Django 5.2.6 on 2025-10-02 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_company_domain_name'),
        ('crm', '0004_leadscore_scoringcriteria_sla_ticketcategory_ticket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_score', models.IntegerField(default=0)),
                ('satisfaction_score', models.IntegerField(default=0)),
                ('usage_score', models.IntegerField(default=0)),
                ('financial_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('health_status', models.CharField(choices=[('excellent', 'Excellent (81-100)'), ('good', 'Good (61-80)'), ('average', 'Average (41-60)'), ('poor', 'Poor (21-40)'), ('critical', 'Critical (0-20)')], default='average', max_length=20)),
                ('churn_risk', models.FloatField(default=0.0)),
                ('upsell_opportunity', models.FloatField(default=0.0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('calculation_count', models.IntegerField(default=0)),
                ('risk_factors', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_score', to='crm.account')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('criteria', models.JSONField(default=dict)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_segments', to='authentication.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='open', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('probability', models.IntegerField(default=0)),
                ('expected_close_date', models.DateField()),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('next_action', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(default=list)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='authentication.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='crm.opportunity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.CharField(max_length=50, unique=True)),
                ('interaction_type', models.CharField(choices=[('email', 'Email'), ('call', 'Phone Call'), ('meeting', 'Meeting'), ('demo', 'Product Demo'), ('support', 'Support Request'), ('purchase', 'Purchase'), ('website_visit', 'Website Visit'), ('social_media', 'Social Media')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('interaction_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_interactions', to='authentication.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_interactions', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='crm.deal')),
            ],
            options={
                'ordering': ['-interaction_date'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('probability', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='authentication.company')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('company', 'order')},
            },
        ),
        migrations.CreateModel(
            name='DealStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='crm.deal')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.pipelinestage')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='current_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.pipelinestage'),
        ),
        migrations.CreateModel(
            name='CustomerSegmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_memberships', to='crm.account')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='crm.customersegment')),
            ],
            options={
                'unique_together': {('segment', 'account')},
            },
        ),
        migrations.CreateModel(
            name='SalesAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('conversion_rate', 'Conversion Rate'), ('avg_deal_size', 'Average Deal Size'), ('sales_cycle_length', 'Sales Cycle Length'), ('win_rate', 'Win Rate'), ('pipeline_velocity', 'Pipeline Velocity'), ('customer_acquisition_cost', 'Customer Acquisition Cost'), ('customer_lifetime_value', 'Customer Lifetime Value')], max_length=30)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_analytics', to='authentication.company')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('company', 'metric_type', 'period', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SalesQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('quota_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('achieved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deals_target', models.IntegerField(default=0)),
                ('deals_achieved', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_quotas', to='authentication.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quotas', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'user', 'period', 'year', 'month', 'quarter')},
            },
        ),
    ]
