# Generated by Django 5.2.6 on 2025-10-03 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_company_domain_name'),
        ('crm', '0006_apiusagelog_automationworkflow_businessintelligence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_id'], name='crm_lead_lead_id_0f5152_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='crm_lead_email_57c21b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'status'], name='crm_lead_company_b1e111_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'priority'], name='crm_lead_assigne_564934_idx'),
        ),
    ]
