# Generated by Django 5.2.9 on 2026-03-23 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_emailactivity_calendarintegration_emailintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='customerinteraction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.account'),
        ),
        migrations.AlterField(
            model_name='customerinteraction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.contact'),
        ),
    ]
