# Generated by Django 5.2.9 on 2026-07-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_percompany_unique_identifiers'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE crm_emailintegration "
                        "ALTER COLUMN credentials TYPE bytea "
                        "USING credentials::text::bytea;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE crm_emailintegration "
                        "ALTER COLUMN credentials TYPE jsonb "
                        "USING credentials::text::jsonb;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='emailintegration',
                    name='credentials',
                    field=models.BinaryField(),
                ),
            ],
        ),
    ]
