# Generated by Django 5.2.9 on 2026-07-02 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_emailintegration_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='crm.account'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='crm.opportunity'),
        ),
    ]
