# Generated by Django 5.2.9 on 2026-07-06 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('crm', '0013_lead_conversion_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='master_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_accounts', to='common.mastercustomer'),
        ),
        migrations.AddField(
            model_name='contact',
            name='master_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_contacts', to='common.mastercustomer'),
        ),
    ]
