# Generated by Django 5.2.9 on 2026-07-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_account_master_customer_contact_master_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailintegration',
            name='credentials',
            field=models.BinaryField(),
        ),
    ]
