# Generated by Django 5.2.9 on 2026-07-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_company_bank_account_holder_and_more'),
        ('crm', '0015_alter_emailintegration_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinteraction',
            name='interaction_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='campaign_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='customerinteraction',
            unique_together={('company', 'interaction_id')},
        ),
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('company', 'deal_id')},
        ),
        migrations.AlterUniqueTogether(
            name='marketingcampaign',
            unique_together={('company', 'campaign_id')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('company', 'ticket_id')},
        ),
    ]
