# Generated by Django 5.2.9 on 2026-07-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_quote_quoteactivity_quotesignature_quotetemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('converted', 'Converted'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
