# Generated by Django 5.2.9 on 2026-07-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Modern Bar'), ('line', 'Trend Line'), ('area', 'Area Trend'), ('pie', 'Donut Share'), ('funnel', 'Sales Funnel')], max_length=20),
        ),
    ]
