# Generated by Django 5.2.9 on 2026-07-08 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_reporttemplate_chart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampaign',
            name='crm_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_runs', to='crm.campaign'),
        ),
    ]
