# Generated by Django 5.2.6 on 2025-09-29 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_add_pan_number_to_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('create_user', 'Create Service User'), ('delete_user', 'Delete Service User'), ('access_service', 'Access Service'), ('update_settings', 'Update Settings'), ('upload_logo', 'Upload Logo'), ('change_password', 'Change Password')], max_length=20)),
                ('description', models.TextField()),
                ('service_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='authentication.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_data_entries', models.BigIntegerField(default=0)),
                ('most_used_service', models.CharField(blank=True, max_length=50)),
                ('least_used_service', models.CharField(blank=True, max_length=50)),
                ('monthly_growth', models.FloatField(default=0.0)),
                ('service_adoption_rate', models.JSONField(default=dict)),
                ('system_health', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Company Analytics',
                'verbose_name_plural': 'Company Analytics',
            },
        ),
        migrations.CreateModel(
            name='CompanyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('service_update', 'Service Update'), ('user_activity', 'User Activity'), ('system_alert', 'System Alert'), ('maintenance', 'Maintenance'), ('security', 'Security Alert')], max_length=20)),
                ('service_type', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Company Notification',
                'verbose_name_plural': 'Company Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_settings', models.JSONField(default=dict)),
                ('feature_toggles', models.JSONField(default=dict)),
                ('access_restrictions', models.JSONField(default=list)),
                ('data_retention_days', models.IntegerField(default=365)),
                ('backup_enabled', models.BooleanField(default=True)),
                ('auto_archive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_configurations', to='authentication.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.service')),
            ],
            options={
                'verbose_name': 'Service Configuration',
                'verbose_name_plural': 'Service Configurations',
                'unique_together': {('company', 'service')},
            },
        ),
        migrations.CreateModel(
            name='ServiceUserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('actions_performed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('session_duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='authentication.companyserviceuser')),
            ],
            options={
                'verbose_name': 'Service User Activity',
                'verbose_name_plural': 'Service User Activities',
                'unique_together': {('service_user', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='ServiceUtilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('usage_percentage', models.FloatField(default=0.0)),
                ('data_volume', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_utilizations', to='authentication.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.service')),
            ],
            options={
                'verbose_name': 'Service Utilization',
                'verbose_name_plural': 'Service Utilizations',
                'unique_together': {('company', 'service')},
            },
        ),
    ]
