# Generated by Django 5.2.6 on 2025-09-29 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_pan_number_to_company'),
        ('company_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(help_text='Official email address for sending emails', max_length=254)),
                ('from_name', models.CharField(help_text='Display name for emails', max_length=255)),
                ('reply_to_email', models.EmailField(blank=True, help_text='Reply-to email address', max_length=254)),
                ('email_provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook/Hotmail'), ('yahoo', 'Yahoo Mail'), ('custom_smtp', 'Custom SMTP'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun'), ('ses', 'Amazon SES')], default='gmail', max_length=20)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('daily_limit', models.IntegerField(default=500, help_text='Daily email sending limit')),
                ('emails_sent_today', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_test_sent', models.DateTimeField(blank=True, null=True)),
                ('test_status', models.CharField(default='pending', max_length=20)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Company Email Settings',
                'verbose_name_plural': 'Company Email Settings',
            },
        ),
    ]
