# Generated by Django 5.2.6 on 2025-09-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_dashboard', '0002_companyemailsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemailsettings',
            name='api_key',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyemailsettings',
            name='api_secret',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyemailsettings',
            name='email_provider',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook/Hotmail'), ('yahoo', 'Yahoo Mail'), ('hostinger', 'Hostinger Email'), ('custom_smtp', 'Custom SMTP'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun'), ('ses', 'Amazon SES')], default='gmail', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyemailsettings',
            name='smtp_password',
            field=models.TextField(blank=True),
        ),
    ]
