# Generated by Django 5.2.6 on 2025-10-09 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_devicefingerprint_loginnotification_securitysettings_and_more'),
        ('company_dashboard', '0003_alter_companyemailsettings_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('success', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'company_login_attempts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CompanyApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key_prefix', models.CharField(max_length=10)),
                ('key_hash', models.CharField(max_length=255)),
                ('permissions', models.JSONField(default=list)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='authentication.company')),
            ],
            options={
                'db_table': 'company_api_keys',
            },
        ),
        migrations.CreateModel(
            name='CompanyPasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='authentication.companyuser')),
            ],
            options={
                'db_table': 'company_password_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=255)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to='authentication.company')),
            ],
            options={
                'db_table': 'company_recovery_codes',
            },
        ),
        migrations.CreateModel(
            name='CompanySecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('2fa_enable', '2FA Enable'), ('2fa_disable', '2FA Disable'), ('api_key_create', 'API Key Create'), ('api_key_delete', 'API Key Delete'), ('ip_restriction_add', 'IP Restriction Add'), ('ip_restriction_remove', 'IP Restriction Remove'), ('session_terminate', 'Session Terminate'), ('failed_login', 'Failed Login'), ('account_locked', 'Account Locked')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField()),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to='authentication.company')),
            ],
            options={
                'db_table': 'company_security_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CompanySecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('ip_restrictions_enabled', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.IntegerField(default=60)),
                ('max_failed_attempts', models.IntegerField(default=5)),
                ('lockout_duration_minutes', models.IntegerField(default=15)),
                ('password_expiry_days', models.IntegerField(default=90)),
                ('require_password_change', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to='authentication.company')),
            ],
            options={
                'db_table': 'company_security_settings',
            },
        ),
        migrations.CreateModel(
            name='CompanyUserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('device_type', models.CharField(default='desktop', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='authentication.companyuser')),
            ],
            options={
                'db_table': 'company_user_sessions',
            },
        ),
        migrations.CreateModel(
            name='CompanyIpRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('restriction_type', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=5)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_restrictions', to='authentication.company')),
            ],
            options={
                'db_table': 'company_ip_restrictions',
                'unique_together': {('company', 'ip_address')},
            },
        ),
    ]
