# Generated by Django 5.2.6 on 2025-10-09 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_companyuser_password_changed_at'),
        ('company_dashboard', '0004_add_security_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAdvancedSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_threat_detection', models.BooleanField(default=True)),
                ('brute_force_threshold', models.IntegerField(default=5)),
                ('velocity_threshold', models.IntegerField(default=10)),
                ('enable_device_fingerprinting', models.BooleanField(default=True)),
                ('auto_trust_devices', models.BooleanField(default=False)),
                ('device_trust_duration_days', models.IntegerField(default=30)),
                ('enable_geolocation_security', models.BooleanField(default=True)),
                ('block_unknown_locations', models.BooleanField(default=False)),
                ('require_2fa_new_locations', models.BooleanField(default=True)),
                ('email_alerts', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=False)),
                ('webhook_alerts', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True)),
                ('auto_block_threats', models.BooleanField(default=True)),
                ('auto_lockout_duration_minutes', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_security_settings', to='authentication.company')),
            ],
            options={
                'db_table': 'company_advanced_security_settings',
            },
        ),
        migrations.CreateModel(
            name='CompanyCaptchaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('failed_attempts_threshold', models.IntegerField(default=3)),
                ('captcha_type', models.CharField(choices=[('recaptcha', 'Google reCAPTCHA'), ('hcaptcha', 'hCaptcha'), ('simple', 'Simple Math Captcha')], default='simple', max_length=20)),
                ('site_key', models.CharField(blank=True, max_length=255)),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='captcha_settings', to='authentication.company')),
            ],
            options={
                'db_table': 'company_captcha_settings',
            },
        ),
        migrations.CreateModel(
            name='CompanyGeolocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('allow', 'Allow'), ('block', 'Block'), ('require_2fa', 'Require 2FA'), ('notify', 'Notify Only')], max_length=20)),
                ('countries', models.JSONField(default=list)),
                ('cities', models.JSONField(default=list)),
                ('ip_ranges', models.JSONField(default=list)),
                ('time_restrictions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geolocation_rules', to='authentication.company')),
            ],
            options={
                'db_table': 'company_geolocation_rules',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanySecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('login_anomaly', 'Login Anomaly'), ('new_device', 'New Device'), ('location_change', 'Location Change'), ('threat_detected', 'Threat Detected'), ('policy_violation', 'Policy Violation'), ('account_lockout', 'Account Lockout'), ('password_breach', 'Password Breach'), ('suspicious_activity', 'Suspicious Activity')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_security_alerts', to='authentication.company')),
            ],
            options={
                'db_table': 'company_security_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyThreatDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('threat_type', models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('suspicious_location', 'Suspicious Location'), ('device_anomaly', 'Device Anomaly'), ('time_anomaly', 'Time-based Anomaly'), ('velocity_attack', 'Velocity Attack'), ('credential_stuffing', 'Credential Stuffing'), ('session_hijacking', 'Session Hijacking'), ('privilege_escalation', 'Privilege Escalation')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('device_id', models.CharField(blank=True, max_length=64)),
                ('is_resolved', models.BooleanField(default=False)),
                ('auto_blocked', models.BooleanField(default=False)),
                ('admin_notified', models.BooleanField(default=False)),
                ('response_actions', models.JSONField(default=list)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_detections', to='authentication.company')),
            ],
            options={
                'db_table': 'company_threat_detections',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('fingerprint_hash', models.CharField(max_length=64)),
                ('user_agent', models.TextField()),
                ('screen_resolution', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('is_trusted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('trust_score', models.IntegerField(default=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('login_count', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_fingerprints', to='authentication.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_fingerprints', to='authentication.companyuser')),
            ],
            options={
                'db_table': 'company_device_fingerprints',
                'unique_together': {('company', 'device_id')},
            },
        ),
    ]
