# Generated by Django 5.2.6 on 2025-10-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_dashboard', '0005_companyadvancedsettings_companycaptchasettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companythreatdetection',
            name='behavioral_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='companythreatdetection',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='companythreatdetection',
            name='ml_model_version',
            field=models.CharField(default='v1.0', max_length=20),
        ),
    ]
