# Generated by Django 5.2.6 on 2025-10-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_dashboard', '0006_add_ai_threat_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysecuritylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
