# Generated by Django 5.2.6 on 2025-10-22 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_make_unique_service_id_required'),
        ('company_dashboard', '0007_alter_companysecuritylog_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGovernmentCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('gst', 'GST API'), ('tds', 'TDS/Income Tax API'), ('einvoice', 'E-Invoice API'), ('eway_bill', 'E-Way Bill API'), ('pf', 'PF API'), ('esi', 'ESI API')], max_length=20)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox/Testing'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('credential_name', models.CharField(help_text='Friendly name for this credential set', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description or notes about this credential')),
                ('client_id', models.TextField(blank=True, help_text='Encrypted client ID')),
                ('client_secret', models.TextField(blank=True, help_text='Encrypted client secret')),
                ('username', models.TextField(blank=True, help_text='Encrypted username')),
                ('password', models.TextField(blank=True, help_text='Encrypted password')),
                ('api_key', models.TextField(blank=True, help_text='Encrypted API key')),
                ('gstin', models.TextField(blank=True, help_text='Encrypted GSTIN')),
                ('pan', models.TextField(blank=True, help_text='Encrypted PAN')),
                ('tan', models.TextField(blank=True, help_text='Encrypted TAN')),
                ('base_url', models.URLField(blank=True, help_text='API base URL')),
                ('additional_config', models.JSONField(default=dict, help_text='Additional API configuration')),
                ('is_active', models.BooleanField(default=False)),
                ('is_validated', models.BooleanField(default=False)),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
                ('validation_error', models.TextField(blank=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.EmailField(help_text='Email of user who created this credential', max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government_credentials', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Company Government Credential',
                'verbose_name_plural': 'Company Government Credentials',
                'db_table': 'company_government_credentials',
                'unique_together': {('company', 'api_type', 'environment')},
            },
        ),
        migrations.CreateModel(
            name='CompanyGovernmentCredentialLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('validate', 'Validated'), ('use', 'Used'), ('activate', 'Activated'), ('deactivate', 'Deactivated')], max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='company_dashboard.companygovernmentcredentials')),
            ],
            options={
                'verbose_name': 'Government Credential Log',
                'verbose_name_plural': 'Government Credential Logs',
                'db_table': 'company_government_credential_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
