# Generated by Django 5.2.6 on 2025-11-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_make_unique_service_id_required'),
        ('company_dashboard', '0008_government_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumberingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('quotation', 'Quotation'), ('purchase_order', 'Purchase Order'), ('invoice', 'Invoice'), ('proforma_invoice', 'Proforma Invoice'), ('payment', 'Payment'), ('customer', 'Customer'), ('vendor', 'Vendor'), ('product', 'Product')], max_length=30)),
                ('financial_year', models.CharField(help_text='Format: 2024-25', max_length=10)),
                ('prefix', models.CharField(help_text='Prefix without year (e.g., QT, PO, INV)', max_length=20)),
                ('starting_number', models.IntegerField(default=1)),
                ('current_counter', models.IntegerField(default=0)),
                ('number_padding', models.IntegerField(default=3, help_text='Number of digits for padding (e.g., 3 for 001)')),
                ('is_active', models.BooleanField(default=True)),
                ('allow_manual_override', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbering_configs', to='authentication.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbering_configs', to='authentication.service')),
            ],
            options={
                'verbose_name': 'Document Numbering Configuration',
                'verbose_name_plural': 'Document Numbering Configurations',
                'ordering': ['-financial_year', 'document_type'],
                'unique_together': {('service', 'company', 'document_type', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='DocumentNumberingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='company_dashboard.documentnumberingconfig')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companyserviceuser')),
            ],
            options={
                'verbose_name': 'Document Numbering History',
                'verbose_name_plural': 'Document Numbering Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialYearSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(help_text='Format: 2024-25', max_length=10)),
                ('start_date', models.DateField(help_text='Financial year start date (usually April 1)')),
                ('end_date', models.DateField(help_text='Financial year end date (usually March 31)')),
                ('is_active', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_year_settings', to='authentication.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_year_settings', to='authentication.service')),
            ],
            options={
                'verbose_name': 'Financial Year Settings',
                'verbose_name_plural': 'Financial Year Settings',
                'ordering': ['-financial_year'],
                'unique_together': {('company', 'service', 'financial_year')},
            },
        ),
    ]
