# Generated by Django 5.2.6 on 2025-11-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_dashboard', '0010_enhance_document_numbering'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDocumentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
