# Generated by Django 5.2.6 on 2025-11-25 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_company_use_document_numbering'),
        ('company_dashboard', '0011_servicedocumenttypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyQuotationTemplateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_template', models.CharField(choices=[('AS', 'AS Template - Clean & Simple'), ('BKGE', 'BKGE Template - Professional'), ('TC', 'TC Template - Detailed Terms')], default='AS', help_text='Template style for all quotations', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_template_settings', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Company Quotation Template Settings',
                'verbose_name_plural': 'Company Quotation Template Settings',
            },
        ),
    ]
