# Generated by Django 5.2.6 on 2025-11-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_dashboard', '0012_add_quotation_template_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyquotationtemplatesettings',
            name='selected_po_template',
            field=models.CharField(choices=[('AS', 'AS Template - Clean & Simple'), ('BKGE', 'BKGE Template - Professional'), ('TC', 'TC Template - Detailed Terms')], default='AS', help_text='Template style for all purchase orders', max_length=10),
        ),
    ]
