# Generated by Django 5.2.6 on 2025-11-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_dashboard', '0013_add_po_template_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyquotationtemplatesettings',
            name='selected_proforma_template',
            field=models.CharField(choices=[('AS', 'AS Template - Clean & Simple'), ('BKGE', 'BKGE Template - Professional'), ('TC', 'TC Template - Detailed Terms')], default='AS', help_text='Template style for all proforma invoices', max_length=10),
        ),
    ]
