# Generated by Django 5.2.6 on 2025-11-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_dashboard', '0014_add_proforma_template_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyquotationtemplatesettings',
            name='selected_invoice_template',
            field=models.CharField(choices=[('AS', 'AS Template - Clean & Simple'), ('BKGE', 'BKGE Template - Professional'), ('TC', 'TC Template - Detailed Terms')], default='AS', help_text='Template style for all invoices', max_length=10),
        ),
    ]
