# Generated by Django 5.2.9 on 2026-03-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_dashboard', '0015_add_invoice_template_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyquotationtemplatesettings',
            name='selected_invoice_template',
            field=models.CharField(choices=[('AS', 'Classic Template - Professional ERP Style'), ('BKGE', 'Modern Template - Clean Whitespace Layout'), ('TC', 'Compact Template - Designed for Many Items')], default='AS', help_text='Template style for all invoices', max_length=10),
        ),
        migrations.AlterField(
            model_name='companyquotationtemplatesettings',
            name='selected_po_template',
            field=models.CharField(choices=[('AS', 'Classic Template - Professional ERP Style'), ('BKGE', 'Modern Template - Clean Whitespace Layout'), ('TC', 'Compact Template - Designed for Many Items')], default='AS', help_text='Template style for all purchase orders', max_length=10),
        ),
        migrations.AlterField(
            model_name='companyquotationtemplatesettings',
            name='selected_proforma_template',
            field=models.CharField(choices=[('AS', 'Classic Template - Professional ERP Style'), ('BKGE', 'Modern Template - Clean Whitespace Layout'), ('TC', 'Compact Template - Designed for Many Items')], default='AS', help_text='Template style for all proforma invoices', max_length=10),
        ),
        migrations.AlterField(
            model_name='companyquotationtemplatesettings',
            name='selected_template',
            field=models.CharField(choices=[('AS', 'Classic Template - Professional ERP Style'), ('BKGE', 'Modern Template - Clean Whitespace Layout'), ('TC', 'Compact Template - Designed for Many Items')], default='AS', help_text='Template style for all quotations', max_length=10),
        ),
    ]
