# Generated by Django 5.2.9 on 2026-07-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_dashboard', '0016_alter_companyquotationtemplatesettings_selected_invoice_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companynotification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
