# Generated by Django 5.2.9 on 2026-07-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_dashboard', '0017_companynotification_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyquotationtemplatesettings',
            name='selected_invoice_template',
            field=models.CharField(choices=[('AS', 'Clean & Simple Template'), ('BKGE', 'Professional Template'), ('TC', 'Detailed Terms Template')], default='AS', help_text='Template style for all invoices', max_length=10),
        ),
        migrations.AlterField(
            model_name='companyquotationtemplatesettings',
            name='selected_po_template',
            field=models.CharField(choices=[('AS', 'Clean & Simple Template'), ('BKGE', 'Professional Template'), ('TC', 'Detailed Terms Template')], default='AS', help_text='Template style for all purchase orders', max_length=10),
        ),
        migrations.AlterField(
            model_name='companyquotationtemplatesettings',
            name='selected_proforma_template',
            field=models.CharField(choices=[('AS', 'Clean & Simple Template'), ('BKGE', 'Professional Template'), ('TC', 'Detailed Terms Template')], default='AS', help_text='Template style for all proforma invoices', max_length=10),
        ),
        migrations.AlterField(
            model_name='companyquotationtemplatesettings',
            name='selected_template',
            field=models.CharField(choices=[('AS', 'Clean & Simple Template'), ('BKGE', 'Professional Template'), ('TC', 'Detailed Terms Template')], default='AS', help_text='Template style for all quotations', max_length=10),
        ),
    ]
