# Generated by Django 5.2.9 on 2026-07-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_dashboard', '0018_alter_companyquotationtemplatesettings_selected_invoice_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentnumberingconfig',
            name='document_type',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('purchase_order', 'Purchase Order'), ('invoice', 'Invoice'), ('proforma_invoice', 'Proforma Invoice'), ('payment', 'Payment'), ('customer', 'Customer'), ('vendor', 'Vendor'), ('product', 'Product'), ('purchase_request', 'Purchase Request'), ('vendor_invoice', 'Vendor Invoice'), ('employee', 'Employee'), ('department', 'Department'), ('designation', 'Designation'), ('attendance', 'Attendance'), ('payroll', 'Payroll'), ('leave_request', 'Leave Request'), ('recruitment', 'Recruitment'), ('performance_review', 'Performance Review'), ('training', 'Training'), ('expense_claim', 'Expense Claim'), ('supplier', 'Supplier'), ('warehouse', 'Warehouse'), ('category', 'Category'), ('bundle', 'Product Bundle'), ('cycle_count', 'Cycle Count'), ('stock_entry', 'Stock Entry'), ('stock_transfer', 'Stock Transfer'), ('stock_adjustment', 'Stock Adjustment'), ('purchase_receipt', 'Purchase Receipt'), ('delivery_note', 'Delivery Note'), ('material_request', 'Material Request'), ('quality_inspection', 'Quality Inspection'), ('lead', 'Lead'), ('contact', 'Contact'), ('account', 'Account'), ('opportunity', 'Opportunity'), ('campaign', 'Campaign'), ('marketing_campaign', 'Marketing Campaign'), ('activity', 'Activity'), ('deal', 'Deal'), ('interaction', 'Interaction'), ('crm_quote', 'CRM Quote'), ('support_ticket', 'Support Ticket'), ('follow_up', 'Follow Up'), ('meeting', 'Meeting'), ('call_log', 'Call Log'), ('audit', 'Audit'), ('asset', 'Asset'), ('project', 'Project'), ('task', 'Task'), ('document', 'Document')], max_length=30),
        ),
    ]
