# Generated by Django 5.2.9 on 2026-07-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_dashboard', '0019_alter_documentnumberingconfig_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentnumberingconfig',
            name='current_counter',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentnumberingconfig',
            name='starting_number',
            field=models.BigIntegerField(default=1),
        ),
    ]
