# Generated by Django 5.2.9 on 2026-07-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_dashboard', '0017_alter_companyquotationtemplatesettings_selected_invoice_template_and_more'),
        ('company_dashboard', '0020_alter_documentnumberingconfig_current_counter_and_more'),
    ]

    operations = [
    ]
