# Generated by Django 5.2.6 on 2025-10-01 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_pan_number_to_company'),
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('validating', 'Validating'), ('ready', 'Ready for Restore'), ('failed', 'Validation Failed')], default='uploading', max_length=20)),
                ('is_valid_backup', models.BooleanField(default=False)),
                ('backup_metadata', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('detected_backup_level', models.CharField(blank=True, max_length=20)),
                ('detected_service_type', models.CharField(blank=True, max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'backup_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('restore_type', models.CharField(choices=[('full_replace', 'Full Replace'), ('selective_merge', 'Selective Merge'), ('company_only', 'Company Data Only'), ('service_only', 'Service Data Only'), ('table_only', 'Specific Tables')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pre_backup', 'Creating Pre-Restore Backup'), ('restoring', 'Restoring Data'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('selected_tables', models.JSONField(blank=True, default=list)),
                ('service_type', models.CharField(blank=True, max_length=20)),
                ('total_steps', models.IntegerField(default=0)),
                ('completed_steps', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('restore_log', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'restore_operations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='backup_level',
            field=models.CharField(choices=[('system', 'Complete System'), ('company', 'Company Data'), ('service', 'Service Data'), ('table', 'Specific Tables'), ('incremental', 'Incremental Changes')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='backup_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.company'),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='is_encrypted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='selected_tables',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='service_type',
            field=models.CharField(choices=[('all', 'All Services'), ('finance', 'Finance Service'), ('hr', 'HR Service'), ('inventory', 'Inventory Service')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='backup_type',
            field=models.CharField(choices=[('full', 'Full Backup'), ('schema', 'Schema Only'), ('data', 'Data Only'), ('selective', 'Selective Tables')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='databasebackup',
            name='backup_type',
            field=models.CharField(choices=[('full', 'Full Backup'), ('schema', 'Schema Only'), ('data', 'Data Only'), ('selective', 'Selective Tables')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='databasebackup',
            name='compression',
            field=models.CharField(choices=[('none', 'No Compression'), ('gzip', 'Gzip Compression'), ('bzip2', 'Bzip2 Compression')], default='gzip', max_length=20),
        ),
        migrations.AlterField(
            model_name='databasebackup',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='databasebackup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='databasebackup',
            index=models.Index(fields=['company', 'backup_level'], name='database_ba_company_e4dcaf_idx'),
        ),
        migrations.AddIndex(
            model_name='databasebackup',
            index=models.Index(fields=['status', 'created_at'], name='database_ba_status_ef6823_idx'),
        ),
        migrations.AddIndex(
            model_name='databasebackup',
            index=models.Index(fields=['backup_level', 'service_type'], name='database_ba_backup__a6e0ad_idx'),
        ),
        migrations.AddField(
            model_name='backupupload',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.company'),
        ),
        migrations.AddField(
            model_name='backupupload',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restoreoperation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.company'),
        ),
        migrations.AddField(
            model_name='restoreoperation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restoreoperation',
            name='pre_restore_backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_operations', to='configuration.databasebackup'),
        ),
        migrations.AddField(
            model_name='restoreoperation',
            name='source_backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.databasebackup'),
        ),
        migrations.AddField(
            model_name='restoreoperation',
            name='source_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.backupupload'),
        ),
    ]
