# Generated by Django 5.2.6 on 2025-09-12 09:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(help_text='Auto-generated unique customer code', max_length=20, unique=True)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('government', 'Government'), ('ngo', 'NGO/Non-Profit')], default='business', max_length=20)),
                ('name', models.CharField(help_text='Customer/Company Name', max_length=255)),
                ('display_name', models.CharField(blank=True, help_text='Display name for invoices', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('website', models.URLField(blank=True)),
                ('billing_address_line1', models.CharField(blank=True, max_length=255)),
                ('billing_address_line2', models.CharField(blank=True, max_length=255)),
                ('billing_city', models.CharField(blank=True, max_length=100)),
                ('billing_state', models.CharField(blank=True, max_length=100)),
                ('billing_pincode', models.CharField(blank=True, max_length=10)),
                ('billing_country', models.CharField(default='India', max_length=100)),
                ('shipping_same_as_billing', models.BooleanField(default=True)),
                ('shipping_address_line1', models.CharField(blank=True, max_length=255)),
                ('shipping_address_line2', models.CharField(blank=True, max_length=255)),
                ('shipping_city', models.CharField(blank=True, max_length=100)),
                ('shipping_state', models.CharField(blank=True, max_length=100)),
                ('shipping_pincode', models.CharField(blank=True, max_length=10)),
                ('shipping_country', models.CharField(blank=True, max_length=100)),
                ('business_type', models.CharField(blank=True, choices=[('proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('llp', 'Limited Liability Partnership'), ('private_limited', 'Private Limited Company'), ('public_limited', 'Public Limited Company'), ('trust', 'Trust'), ('society', 'Society'), ('cooperative', 'Cooperative Society'), ('other', 'Other')], max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('gstin', models.CharField(blank=True, help_text='15-digit GST Identification Number', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid GSTIN number', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('pan_number', models.CharField(blank=True, help_text='10-character PAN number', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('aadhar_number', models.CharField(blank=True, help_text='12-digit Aadhar number (for individuals)', max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid 12-digit Aadhar number', regex='^[0-9]{12}$')])),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('payment_terms', models.CharField(blank=True, help_text='e.g., Net 30, COD, Advance', max_length=100)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the customer')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_customers', to='authentication.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_customers', to='authentication.companyserviceuser')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'customer_code')},
            },
        ),
    ]
