# Generated by Django 5.2.6 on 2025-10-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_company_domain_name'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='finance_inv_invoice_dd3aad_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'invoice_date'], name='finance_inv_company_e02829_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'payment_status'], name='finance_inv_custome_e9fc23_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'created_at'], name='finance_inv_status_7d718d_idx'),
        ),
    ]
