# Generated by Django 5.2.6 on 2025-09-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='claim_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage-based Claiming'), ('quantity', 'Quantity-based Claiming')], help_text='How proforma invoices will be claimed from this PO (set on first invoice creation)', max_length=20, null=True),
        ),
    ]
