# Generated by Django 5.2.6 on 2025-09-12 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_company_logo'),
        ('finance', '0002_customershippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSNCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('description', models.TextField()),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_hsn_codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SACCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('service_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_sac_codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('product', 'Product (Goods)'), ('service', 'Service')], default='product', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('gm', 'Grams'), ('ltr', 'Liters'), ('mtr', 'Meters'), ('sqft', 'Square Feet'), ('hrs', 'Hours'), ('days', 'Days'), ('box', 'Box'), ('set', 'Set')], default='pcs', max_length=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('track_inventory', models.BooleanField(default=False)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to='authentication.companyserviceuser')),
                ('hsn_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='finance.hsncode')),
                ('sac_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='finance.saccode')),
            ],
            options={
                'db_table': 'finance_products',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'product_code')},
            },
        ),
    ]
