# Generated by Django 5.2.6 on 2025-10-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gst_registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_gst_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_code',
            field=models.CharField(blank=True, help_text='2-digit state code for GST', max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_transaction_id',
            field=models.CharField(blank=True, help_text='Unique GST transaction ID', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gstr1_filing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_filed_in_gstr1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='place_of_supply',
            field=models.CharField(blank=True, help_text='State code where supply is made', max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reverse_charge_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='form16a_number',
            field=models.CharField(blank=True, help_text='Form 16A certificate number', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='tds_certificate_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='tds_challan_number',
            field=models.CharField(blank=True, help_text='TDS challan number', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='tds_deposited_date',
            field=models.DateField(blank=True, help_text='Date when TDS was deposited', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tds_rate_applied',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='TDS rate applied', max_digits=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='tds_section_code',
            field=models.CharField(blank=True, help_text='TDS section code (194A, 194C, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='gst_transaction_id',
            field=models.CharField(blank=True, help_text='Unique GST transaction ID', max_length=50),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='place_of_supply',
            field=models.CharField(blank=True, help_text='State code where supply is made', max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, help_text='Auto-generated unique customer code', max_length=20, unique=True),
        ),
    ]
