# Generated by Django 5.2.6 on 2025-09-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_hsncode_saccode_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsncode',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='saccode',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
