# Generated by Django 5.2.6 on 2025-10-04 13:37

import django.db.models.deletion
import finance.document_models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_companyuser_password_reset_by_admin'),
        ('finance', '0003_indian_compliance_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('generate_invoices', 'Generate Invoices'), ('generate_einvoices', 'Generate E-Invoices'), ('send_documents', 'Send Documents'), ('archive_documents', 'Archive Documents')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_items', models.PositiveIntegerField()),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_details', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_operations', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companyserviceuser')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('proforma', 'Proforma Invoice'), ('quotation', 'Quotation'), ('payment_receipt', 'Payment Receipt'), ('tds_certificate', 'TDS Certificate'), ('gst_return', 'GST Return'), ('einvoice', 'E-Invoice'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('file_path', models.FileField(upload_to=finance.document_models.document_upload_path)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('signed', 'Digitally Signed'), ('sent', 'Sent'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_digitally_signed', models.BooleanField(default=False)),
                ('signature_timestamp', models.DateTimeField(blank=True, null=True)),
                ('signature_certificate', models.TextField(blank=True)),
                ('einvoice_irn', models.CharField(blank=True, max_length=100)),
                ('einvoice_ack_no', models.CharField(blank=True, max_length=100)),
                ('einvoice_ack_date', models.DateTimeField(blank=True, null=True)),
                ('qr_code_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companyserviceuser')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.payment')),
                ('proforma_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.proformainvoice')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('invoice', 'Invoice Template'), ('proforma', 'Proforma Invoice Template'), ('quotation', 'Quotation Template'), ('payment_receipt', 'Payment Receipt Template'), ('tds_certificate', 'TDS Certificate Template'), ('gst_return', 'GST Return Template')], max_length=50)),
                ('html_content', models.TextField()),
                ('css_styles', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companyserviceuser')),
            ],
            options={
                'unique_together': {('company', 'template_type', 'is_default')},
            },
        ),
    ]
