# Generated by Django 5.2.6 on 2025-09-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_hsncode_code_alter_saccode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsncode',
            name='code',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='saccode',
            name='code',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
