# Generated by Django 5.2.6 on 2025-09-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_hsncode_code_alter_saccode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('PCS', 'Pieces'), ('KG', 'Kilograms'), ('GM', 'Grams'), ('LITER', 'Liters'), ('METER', 'Meters'), ('SQFT', 'Square Feet'), ('HOUR', 'Hours'), ('DAY', 'Days'), ('MONTH', 'Months'), ('YEAR', 'Years'), ('BOX', 'Box'), ('SET', 'Set')], default='PCS', max_length=10),
        ),
    ]
