# Generated by Django 5.2.6 on 2025-10-07 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_bankaccount_emailautomation_erpintegration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('is_matched', models.BooleanField(default=False)),
                ('match_confidence', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('import_batch_id', models.CharField(blank=True, max_length=50)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='finance.customer')),
                ('matched_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.payment')),
            ],
            options={
                'db_table': 'finance_customer_bank_statements',
                'ordering': ['-transaction_date'],
                'unique_together': {('customer', 'transaction_date', 'reference_number')},
            },
        ),
    ]
