# Generated by Django 5.2.6 on 2025-10-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_add_customer_bank_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_statement_import',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='statement_import_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
