# Generated by Django 5.2.6 on 2025-09-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_quotation_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='project_area',
            field=models.CharField(blank=True, help_text='Project area or address label for easy identification', max_length=255),
        ),
    ]
