# Generated by Django 5.2.6 on 2025-09-13 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_company_logo'),
        ('finance', '0008_customer_project_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_revised',
            field=models.BooleanField(default=False, help_text='Whether this quotation has been revised'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='revised_at',
            field=models.DateTimeField(blank=True, help_text='When this quotation was last revised', null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='revised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revised_quotations', to='authentication.companyserviceuser'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='revision_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this quotation has been revised'),
        ),
    ]
