# Generated by Django 5.2.6 on 2025-09-13 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_company_logo'),
        ('finance', '0009_add_revision_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(help_text="Client's PO/WO number", max_length=100)),
                ('po_date', models.DateField(help_text="Client's PO/WO date")),
                ('po_file', models.FileField(blank=True, help_text="Client's PO/WO file attachment", null=True, upload_to='po_files/')),
                ('internal_po_number', models.CharField(db_index=True, help_text='Our internal PO number', max_length=50, unique=True)),
                ('quotation_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('reference', models.CharField(blank=True, help_text='Customer reference or PO number', max_length=100)),
                ('gst_type', models.CharField(choices=[('igst', 'IGST (Inter-State)'), ('cgst_sgst', 'CGST + SGST (Intra-State)'), ('exempt', 'GST Exempt')], max_length=20)),
                ('customer_gstin', models.CharField(blank=True, help_text='Customer GSTIN at time of PO', max_length=15)),
                ('company_gstin', models.CharField(blank=True, help_text='Company GSTIN at time of PO', max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to='authentication.companyserviceuser')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='finance.customer')),
                ('quotation', models.ForeignKey(help_text='Original quotation this PO is based on', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='finance.quotation')),
                ('shipping_address', models.ForeignKey(blank=True, help_text='Selected shipping address for this PO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.customershippingaddress')),
            ],
            options={
                'db_table': 'finance_purchase_orders',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'internal_po_number')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_items', to='finance.purchaseorder')),
            ],
            options={
                'db_table': 'finance_purchase_order_items',
                'ordering': ['line_number'],
                'unique_together': {('purchase_order', 'line_number')},
            },
        ),
    ]
