# Generated by Django 5.2.6 on 2025-09-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_company_logo'),
        ('finance', '0011_add_approved_status_to_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proforma_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('proforma_date', models.DateField()),
                ('due_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('customer_gstin', models.CharField(blank=True, max_length=15)),
                ('company_gstin', models.CharField(blank=True, max_length=15)),
                ('gst_type', models.CharField(choices=[('igst', 'IGST'), ('cgst_sgst', 'CGST + SGST'), ('exempt', 'GST Exempt')], default='igst', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Customer'), ('approved', 'Approved by Customer'), ('converted', 'Converted to Invoice'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proforma_invoices', to='authentication.companyserviceuser')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.customer')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoices', to='finance.purchaseorder')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.customershippingaddress')),
            ],
            options={
                'db_table': 'finance_proforma_invoices',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'proforma_number')},
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.product')),
                ('proforma_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proforma_items', to='finance.proformainvoice')),
            ],
            options={
                'db_table': 'finance_proforma_invoice_items',
                'ordering': ['line_number'],
                'unique_together': {('proforma_invoice', 'line_number')},
            },
        ),
    ]
