# Generated by Django 5.2.6 on 2025-10-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_revert_payment_customer_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Opening balance for this customer', max_digits=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='opening_balance_date',
            field=models.DateField(blank=True, help_text='Date when opening balance was set', null=True),
        ),
    ]
