# Generated by Django 5.2.6 on 2025-11-13 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_vendor_purchaserequest_vendorinvoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhar number (for individuals)', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 12-digit Aadhar number', regex='^[0-9]{12}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code', regex='^[A-Z]{4}0[A-Z0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_address_line1',
            field=models.CharField(help_text='MANDATORY: Billing address line 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_city',
            field=models.CharField(help_text='MANDATORY: Billing city', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_pincode',
            field=models.CharField(help_text='MANDATORY: Billing PIN code', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_state',
            field=models.CharField(help_text='MANDATORY: Billing state', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='business_type',
            field=models.CharField(blank=True, choices=[('proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('llp', 'Limited Liability Partnership'), ('private_limited', 'Private Limited Company'), ('public_limited', 'Public Limited Company'), ('trust', 'Trust'), ('society', 'Society'), ('cooperative', 'Cooperative Society'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('government', 'Government'), ('ngo', 'NGO/Non-Profit')], help_text='MANDATORY: Customer type', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='display_name',
            field=models.CharField(help_text='MANDATORY: Display name for invoices', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gstin',
            field=models.CharField(help_text='MANDATORY: 15-digit GST Identification Number', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid GSTIN number', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='MANDATORY: Customer/Company Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the customer', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pan_number',
            field=models.CharField(blank=True, help_text='10-character PAN number', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='e.g., Net 30, COD, Advance', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='MANDATORY: Primary phone number', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='project_area',
            field=models.CharField(blank=True, help_text='Project area or address label for easy identification', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state_code',
            field=models.CharField(blank=True, help_text='2-digit state code for GST', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
