# Generated by Django 5.2.6 on 2025-09-15 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_invoice_invoiceitem_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.purchaseorder'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='claim_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of PO claimed (for percentage-based)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='claim_type',
            field=models.CharField(choices=[('percentage', 'Percentage-based'), ('quantity', 'Quantity-based')], default='percentage', help_text='Type of claim from PO', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='is_advance_bill',
            field=models.BooleanField(default=True, help_text='True for proforma (advance bill without tax), False for final invoice'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='claim_type',
            field=models.CharField(choices=[('percentage', 'Percentage-based Claiming'), ('quantity', 'Quantity-based Claiming')], default='percentage', help_text='How proforma invoices will be claimed from this PO', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='invoice_claimed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount invoiced (final invoices with tax)', max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='invoice_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('partial', 'Partially Invoiced'), ('completed', 'Fully Invoiced')], default='not_started', help_text='Status of final invoicing', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='proforma_claimed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount claimed through proforma invoices', max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='proforma_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('partial', 'Partially Claimed'), ('completed', 'Fully Claimed')], default='not_started', help_text='Status of proforma invoice claiming', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='remaining_invoice_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining amount to be invoiced (with tax)', max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='remaining_proforma_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining amount available for proforma claiming', max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='invoice_claimed_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity invoiced through final invoices', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='proforma_claimed_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity claimed through proforma invoices', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='proforma_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.proformainvoice'),
        ),
    ]
