# Generated by Django 5.2.6 on 2025-09-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_invoice_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('tax_invoice', 'Tax Invoice'), ('proforma', 'Proforma Invoice'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note')], default='tax_invoice', help_text='Type of invoice', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_payment_date',
            field=models.DateField(blank=True, help_text='Date of last payment received', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='Payment due date', null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='last_payment_date',
            field=models.DateField(blank=True, help_text='Date of last payment received', null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Outstanding amount for this proforma invoice', max_digits=15),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid against this proforma invoice', max_digits=15),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Fully Paid'), ('overdue', 'Overdue')], default='unpaid', help_text='Payment status of this proforma invoice', max_length=20),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Customer'), ('approved', 'Approved by Customer'), ('paid', 'Fully Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
