# Generated by Django 5.2.6 on 2025-11-17 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_update_customer_mandatory_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='quotation',
            field=models.ForeignKey(blank=True, help_text='Original quotation this PO is based on (optional for direct POs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='finance.quotation'),
        ),
    ]
