# Generated by Django 5.2.6 on 2025-11-18 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_make_quotation_optional_in_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformainvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoices', to='finance.purchaseorder'),
        ),
    ]
