# Generated by Django 5.2.6 on 2025-09-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_add_world_class_payment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_tds_received',
            field=models.BooleanField(default=False, help_text='Whether TDS certificate/refund is received'),
        ),
        migrations.AddField(
            model_name='payment',
            name='net_amount_received',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount received after TDS deduction', max_digits=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='TDS amount deducted', max_digits=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='tds_certificate_date',
            field=models.DateField(blank=True, help_text='TDS certificate date', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tds_certificate_number',
            field=models.CharField(blank=True, help_text='TDS certificate number', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='tds_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='TDS percentage applied', max_digits=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='tds_section',
            field=models.CharField(blank=True, help_text='TDS section (194C, 194J, etc.)', max_length=20),
        ),
    ]
