# Generated by Django 5.2.6 on 2025-11-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_make_purchase_order_nullable_in_proforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary phone number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('NOS', 'Numbers'), ('PCS', 'Pieces'), ('KG', 'Kilograms'), ('GM', 'Grams'), ('LITER', 'Liters'), ('METER', 'Meters'), ('SQFT', 'Square Feet'), ('HOUR', 'Hours'), ('DAY', 'Days'), ('MONTH', 'Months'), ('YEAR', 'Years'), ('BOX', 'Box'), ('SET', 'Set')], default='PCS', max_length=10),
        ),
    ]
