# Generated by Django 5.2.6 on 2025-11-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_make_phone_optional_in_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('NOS', 'Numbers'), ('PCS', 'Pieces'), ('KG', 'Kilograms'), ('GM', 'Grams'), ('LITER', 'Liters'), ('METER', 'Meters'), ('SQFT', 'Square Feet'), ('HOUR', 'Hours'), ('DAY', 'Days'), ('MONTH', 'Months'), ('YEAR', 'Years'), ('BOX', 'Box'), ('SET', 'Set')], default='PCS', max_length=10),
        ),
    ]
