# Generated by Django 5.2.6 on 2025-11-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_make_product_unit_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manual_gst_override',
            field=models.BooleanField(default=False, help_text='True if GST rate was manually overridden'),
        ),
    ]
