# Generated by Django 5.2.6 on 2025-11-19 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_make_unique_service_id_required'),
        ('finance', '0019_product_manual_gst_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unit code (e.g., KG, PCS, LITER)', max_length=20)),
                ('name', models.CharField(help_text='Unit display name (e.g., Kilograms, Pieces, Liters)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_units', to='authentication.companyserviceuser')),
            ],
            options={
                'db_table': 'finance_units',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='finance.unit'),
        ),
    ]
