# Generated by Django 5.2.6 on 2025-11-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_alter_product_unit_unit_product_unit_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='quotation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
