# Generated by Django 5.2.6 on 2025-11-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_make_po_dates_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
