# Generated by Django 5.2.6 on 2025-11-22 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_make_invoice_due_date_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quotation',
            field=models.ForeignKey(blank=True, help_text='Quotation this invoice is created from (if not from PO)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.quotation'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='quotation',
            field=models.ForeignKey(blank=True, help_text='Quotation this proforma is created from (if not from PO)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoices', to='finance.quotation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='invoice_created',
            field=models.BooleanField(default=False, help_text='Whether invoice has been created from this quotation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='invoice_created_at',
            field=models.DateTimeField(blank=True, help_text='When invoice was created from this quotation', null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='po_created',
            field=models.BooleanField(default=False, help_text='Whether PO has been created from this quotation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='po_created_at',
            field=models.DateTimeField(blank=True, help_text='When PO was created from this quotation', null=True),
        ),
    ]
