# Generated by Django 5.2.6 on 2025-11-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_invoice_quotation_proformainvoice_quotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='claim_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage-based Claiming'), ('quantity', 'Quantity-based Claiming')], help_text='How invoices will be claimed from this quotation (set on first invoice creation)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='invoice_claimed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount invoiced (final invoices with tax) from this quotation', max_digits=15),
        ),
        migrations.AddField(
            model_name='quotation',
            name='proforma_claimed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount claimed through proforma invoices from this quotation', max_digits=15),
        ),
        migrations.AddField(
            model_name='quotation',
            name='remaining_invoice_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining amount to be invoiced (with tax) from quotation', max_digits=15),
        ),
        migrations.AddField(
            model_name='quotation',
            name='remaining_proforma_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining amount available for proforma claiming from quotation', max_digits=15),
        ),
    ]
