# Generated by Django 5.2.6 on 2025-11-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_add_quotation_balance_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='proforma_created',
            field=models.BooleanField(default=False, help_text='Whether proforma invoice has been created from this quotation'),
        ),
    ]
