# Generated by Django 5.2.6 on 2025-11-24 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_company_use_document_numbering'),
        ('finance', '0025_quotation_proforma_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Whether this invoice has been rejected'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When this invoice was rejected', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_invoices', to='authentication.companyserviceuser'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection', null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Whether this proforma invoice has been rejected'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When this proforma invoice was rejected', null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_proforma_invoices', to='authentication.companyserviceuser'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Customer'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Customer'), ('approved', 'Approved by Customer'), ('paid', 'Fully Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
