# Generated by Django 5.2.6 on 2025-11-24 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_company_use_document_numbering'),
        ('finance', '0026_invoice_is_rejected_invoice_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Whether this quotation has been rejected'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When this quotation was rejected', null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_quotations', to='authentication.companyserviceuser'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection', null=True),
        ),
    ]
