# Generated by Django 5.2.6 on 2025-11-24 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_company_use_document_numbering'),
        ('finance', '0027_quotation_is_rejected_quotation_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_revised',
            field=models.BooleanField(default=False, help_text='Whether this invoice has been revised'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='revised_at',
            field=models.DateTimeField(blank=True, help_text='When this invoice was last revised', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='revised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revised_invoices', to='authentication.companyserviceuser'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='revision_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this invoice has been revised'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='is_revised',
            field=models.BooleanField(default=False, help_text='Whether this proforma invoice has been revised'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='revised_at',
            field=models.DateTimeField(blank=True, help_text='When this proforma invoice was last revised', null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='revised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revised_proforma_invoices', to='authentication.companyserviceuser'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='revision_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this proforma invoice has been revised'),
        ),
    ]
