# Generated by Django 5.2.9 on 2026-03-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_remove_invoice_status_update_po_status'),
        ('finance', '0029_finance_numbering_foundations'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='finance_inv_status_7d718d_idx',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('partially_completed', 'Partially Completed'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='finance_inv_created_441ab3_idx'),
        ),
    ]
