# Generated by Django 5.2.9 on 2026-03-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_remove_invoice_status_update_po_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformainvoice',
            name='status',
        ),
    ]
