# Generated by Django 5.2.9 on 2026-03-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_invoice_is_work_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst_paid_date',
            field=models.DateField(blank=True, help_text='Date GST was remitted to government', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_payment_reference',
            field=models.CharField(blank=True, help_text='Challan/reference number for GST payment', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('not_applicable', 'Not Applicable')], default='pending', help_text='Whether GST collected on this invoice has been remitted to government', max_length=20),
        ),
    ]
