# Generated by Django 5.2.9 on 2026-03-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_invoice_gst_payment_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ca_acknowledgment_number',
            field=models.CharField(blank=True, help_text='CA acknowledgment/reference number', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='ca_firm',
            field=models.CharField(blank=True, help_text='CA Firm name', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='ca_membership_number',
            field=models.CharField(blank=True, help_text='ICAI membership number', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='ca_name',
            field=models.CharField(blank=True, help_text='Name of Chartered Accountant', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='ca_notes',
            field=models.TextField(blank=True, help_text='Notes about CA submission, follow-ups, etc.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='ca_submission_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted to CA'), ('acknowledged', 'Acknowledged by CA'), ('returned', 'Returned by CA')], default='not_submitted', help_text='Status of TDS certificate submission to CA', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_to_ca_date',
            field=models.DateField(blank=True, help_text='Date when TDS certificate was submitted to CA', null=True),
        ),
    ]
