# Generated by Django 5.2.9 on 2026-03-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_add_ca_tds_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ca_notes',
            field=models.TextField(blank=True, help_text='Notes about CA submission, follow-ups, quarterly filings, etc.'),
        ),
    ]
