# Generated by Django 5.2.9 on 2026-03-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0035_add_ca_level_tds_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_tds_received',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tds_certificate_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tds_certificate_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tds_percentage',
        ),
        migrations.AddField(
            model_name='payment',
            name='gross_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Gross amount customer is paying', max_digits=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='tds_applicable',
            field=models.BooleanField(default=False, help_text='Whether TDS applies to this payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tds_certificate_received',
            field=models.BooleanField(default=False, help_text='Whether TDS certificate (Form 16A) has been received'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tds_deposited',
            field=models.BooleanField(default=False, help_text='Whether TDS has been deposited to government'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tds_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='TDS rate percentage', max_digits=5),
        ),
    ]
