# Generated by Django 5.2.9 on 2026-03-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0037_add_tds_deposits'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tds_applicable',
            field=models.BooleanField(default=False, help_text='Whether TDS applies to payments on this invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tds_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='TDS rate percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tds_section',
            field=models.CharField(blank=True, help_text='TDS section code (194C, 194J, etc.)', max_length=20),
        ),
    ]
