# Generated by Django 5.2.9 on 2026-04-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0038_invoice_tds_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('confirmed', 'Confirmed'), ('approved', 'Approved'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted', 'Converted to Invoice')], default='draft', max_length=20),
        ),
    ]
