# Generated by Django 5.2.9 on 2026-04-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0039_add_confirmed_po_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, help_text='Auto-generated unique customer code (e.g., TC-CUST-2627-001)', max_length=40, unique=True),
        ),
    ]
