# Generated by Django 5.2.9 on 2026-04-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0037_add_direct_customer_payment'),
        ('finance', '0999_add_shipping_address_snapshot'),
    ]

    operations = [
    ]
