# Generated by Django 5.2.9 on 2026-05-11 12:16

import django.db.models.deletion
import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '1003_add_company_scoped_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_address_snapshot',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_label',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_line1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_line2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_pincode',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_state',
        ),
        migrations.AddField(
            model_name='invoice',
            name='claim_method',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('as_per_unit', 'As Per Unit')], default='percentage', help_text='How the claim was made', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='claim_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage claimed from PO/Quotation', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='claim_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('unit', 'Unit'), ('as_per_unit', 'As Per Unit')], help_text='Type of claim', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='claimed_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage claimed if claim_type is percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='claimed_quantity_display',
            field=models.CharField(blank=True, help_text="Display value for claimed quantity (e.g., '10%' or '5 Nos')", max_length=50),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='is_claimed',
            field=models.BooleanField(default=False, help_text='Whether this line item has been claimed'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='finance.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='TDS amount to be collected from client', max_digits=15),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tds_applicable',
            field=models.BooleanField(default=False, help_text='Whether TDS applies to this quotation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tds_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='TDS percentage to be collected from client', max_digits=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gstin',
            field=models.CharField(blank=True, help_text='15-digit GST Identification Number (required only if GST registered)', max_length=15, null=True, validators=[finance.models.validate_gstin_optional]),
        ),
        migrations.AlterField(
            model_name='numberingrule',
            name='module',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('purchase_order', 'Purchase Order'), ('proforma_invoice', 'Proforma Invoice'), ('invoice', 'Invoice'), ('customer_payment', 'Customer Payment'), ('purchase_request', 'Purchase Request'), ('purchase_payment', 'Purchase Payment'), ('vendor_invoice', 'Vendor Invoice'), ('customer', 'Customer'), ('vendor', 'Vendor'), ('product', 'Product')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_purpose',
            field=models.CharField(blank=True, help_text='Purpose of direct payment (memo, penalty, incentive, complimentary, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('invoice', 'Invoice Payment'), ('direct', 'Direct Payment'), ('tds_only', 'TDS Only Payment')], default='invoice', help_text='Type of payment - linked to invoice or direct', max_length=20),
        ),
    ]
