# Generated by Django 5.2.9 on 2026-07-06 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('finance', '1004_add_tds_to_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='master_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_customers', to='common.mastercustomer'),
        ),
        migrations.AddField(
            model_name='product',
            name='master_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_products', to='common.masterproduct'),
        ),
    ]
