# Generated by Django 5.2.9 on 2026-07-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '1005_customer_master_customer_product_master_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated unique customer code (e.g., TC-CUST-2627-001)', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
