# Generated by Django 5.2.9 on 2026-07-14 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '1005_add_gstr1_fields'),
        ('finance', '1007_remove_customer_master_customer_and_more'),
    ]

    operations = [
    ]
