# Generated by Django 5.2.9 on 2026-07-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '1008_merge_20260714_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='cess_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ecommerce_gstin',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='gst_supply_type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='gstr1_excluded',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_amendment',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='original_document_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='original_document_number',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='cess_amount',
        ),
    ]
