# Generated by Django 5.2.6 on 2025-10-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_make_unique_service_id_required'),
        ('inventory', '0003_add_enhanced_features'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productbundle',
            name='unique_company_bundle_code',
        ),
        migrations.RemoveConstraint(
            model_name='productbundleitem',
            name='unique_bundle_product',
        ),
        migrations.AlterUniqueTogether(
            name='productbundle',
            unique_together={('company', 'bundle_code')},
        ),
        migrations.AlterUniqueTogether(
            name='productbundleitem',
            unique_together={('bundle', 'product')},
        ),
    ]
