# Generated by Django 5.2.9 on 2026-07-06 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('inventory', '0004_remove_productbundle_unique_company_bundle_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='master_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_products', to='common.masterproduct'),
        ),
    ]
