# Generated by Django 5.2.9 on 2026-07-06 08:22

from django.db import migrations, models


def blank_barcodes_to_null(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    ProductVariant = apps.get_model('inventory', 'ProductVariant')
    Product.objects.filter(barcode='').update(barcode=None)
    ProductVariant.objects.filter(barcode='').update(barcode=None)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_master_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(blank_barcodes_to_null, migrations.RunPython.noop),
    ]
