# Generated by Django 5.2.9 on 2026-07-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_company_bank_account_holder_and_more'),
        ('inventory', '0006_alter_product_barcode_alter_productvariant_barcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'product_code')},
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cyclecount',
            name='count_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryaudit',
            name='audit_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Stock Keeping Unit', max_length=50),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='bundle_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='cyclecount',
            unique_together={('company', 'count_number')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryaudit',
            unique_together={('company', 'audit_number')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'product_code'), ('company', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('company', 'po_number')},
        ),
    ]
