# Generated by Django 5.2.6 on 2025-09-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(max_length=100, unique=True)),
                ('repository', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=100)),
                ('commit_hash', models.CharField(max_length=40)),
                ('commit_message', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('rollback', 'Rollback')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('logs', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('rollback_commit', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
