# Generated by Django 5.2.9 on 2026-07-06 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0023_company_bank_account_holder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSharingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_to_finance_customers', models.BooleanField(default=False)),
                ('finance_to_crm_customers', models.BooleanField(default=False)),
                ('inventory_to_finance_products', models.BooleanField(default=False)),
                ('finance_to_inventory_products', models.BooleanField(default=False)),
                ('crm_opportunity_to_finance_quotation', models.BooleanField(default=False)),
                ('auto_sync_enabled', models.BooleanField(default=False)),
                ('require_manual_approval', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_sharing_policy', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Data Sharing Policy',
                'verbose_name_plural': 'Data Sharing Policies',
                'db_table': 'common_data_sharing_policies',
            },
        ),
        migrations.CreateModel(
            name='MasterCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_code', models.CharField(db_index=True, max_length=50)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('government', 'Government'), ('ngo', 'NGO/Non-Profit'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('billing_address_line1', models.CharField(blank=True, max_length=255)),
                ('billing_address_line2', models.CharField(blank=True, max_length=255)),
                ('billing_city', models.CharField(blank=True, max_length=100)),
                ('billing_state', models.CharField(blank=True, max_length=100)),
                ('billing_pincode', models.CharField(blank=True, max_length=10)),
                ('billing_country', models.CharField(default='India', max_length=100)),
                ('source_module', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_customers', to='authentication.company')),
            ],
            options={
                'db_table': 'common_master_customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MasterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('raw_material', 'Raw Material'), ('finished_good', 'Finished Good'), ('digital', 'Digital Product'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('sac_code', models.CharField(blank=True, max_length=20)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('base_unit', models.CharField(blank=True, max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_stock_tracked', models.BooleanField(default=False)),
                ('source_module', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_products', to='authentication.company')),
            ],
            options={
                'db_table': 'common_master_products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDataLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=30)),
                ('object_model', models.CharField(max_length=100)),
                ('object_id', models.PositiveBigIntegerField()),
                ('sync_status', models.CharField(choices=[('linked', 'Linked'), ('pending', 'Pending'), ('conflict', 'Conflict'), ('disabled', 'Disabled')], default='linked', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_data_links', to='authentication.company')),
                ('master_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='common.mastercustomer')),
                ('master_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='common.masterproduct')),
            ],
            options={
                'db_table': 'common_service_data_links',
            },
        ),
        migrations.AddIndex(
            model_name='mastercustomer',
            index=models.Index(fields=['company', 'name'], name='common_mast_company_605ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='mastercustomer',
            index=models.Index(fields=['company', 'email'], name='common_mast_company_edd392_idx'),
        ),
        migrations.AddIndex(
            model_name='mastercustomer',
            index=models.Index(fields=['company', 'gstin'], name='common_mast_company_fe6328_idx'),
        ),
        migrations.AddIndex(
            model_name='mastercustomer',
            index=models.Index(fields=['company', 'is_active'], name='common_mast_company_56041a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mastercustomer',
            unique_together={('company', 'master_code')},
        ),
        migrations.AddIndex(
            model_name='masterproduct',
            index=models.Index(fields=['company', 'name'], name='common_mast_company_15ac1e_idx'),
        ),
        migrations.AddIndex(
            model_name='masterproduct',
            index=models.Index(fields=['company', 'master_code'], name='common_mast_company_541de7_idx'),
        ),
        migrations.AddIndex(
            model_name='masterproduct',
            index=models.Index(fields=['company', 'is_active'], name='common_mast_company_9c0c6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='masterproduct',
            unique_together={('company', 'master_code')},
        ),
        migrations.AddIndex(
            model_name='servicedatalink',
            index=models.Index(fields=['company', 'service_type'], name='common_serv_company_f97057_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedatalink',
            index=models.Index(fields=['object_model', 'object_id'], name='common_serv_object__c9ef1b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedatalink',
            index=models.Index(fields=['sync_status'], name='common_serv_sync_st_0187a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicedatalink',
            unique_together={('service_type', 'object_model', 'object_id')},
        ),
    ]
