# Generated by Django 5.2.9 on 2026-07-06 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_company_bank_account_holder_and_more'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('crm_account_to_finance_customer', 'CRM account to Finance customer'), ('crm_contact_to_finance_customer', 'CRM contact to Finance customer'), ('finance_customer_to_crm_account', 'Finance customer to CRM account'), ('inventory_product_to_finance_product', 'Inventory product to Finance product'), ('finance_product_to_inventory_product', 'Finance product to Inventory product')], max_length=60)),
                ('source_service', models.CharField(max_length=30)),
                ('target_service', models.CharField(max_length=30)),
                ('source_model', models.CharField(max_length=100)),
                ('source_object_id', models.PositiveBigIntegerField()),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('suggested_data', models.JSONField(blank=True, default=dict)),
                ('approval_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_approval_requests', to='authentication.company')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sync_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'common_sync_approval_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='common_sync_company_23f060_idx'), models.Index(fields=['request_type'], name='common_sync_request_8d3066_idx'), models.Index(fields=['source_model', 'source_object_id'], name='common_sync_source__662fd2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('request_type', 'source_model', 'source_object_id', 'status'), name='common_sync_one_pending_per_source')],
            },
        ),
    ]
