# Generated by Django 5.2.9 on 2026-07-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_syncapprovalrequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncapprovalrequest',
            name='request_type',
            field=models.CharField(choices=[('crm_account_to_finance_customer', 'CRM account to Finance customer'), ('crm_contact_to_finance_customer', 'CRM contact to Finance customer'), ('finance_customer_to_crm_account', 'Finance customer to CRM account'), ('finance_customer_to_crm_contact', 'Finance customer to CRM contact'), ('inventory_product_to_finance_product', 'Inventory product to Finance product'), ('finance_product_to_inventory_product', 'Finance product to Inventory product'), ('delete_shared_record', 'Delete shared record')], max_length=60),
        ),
    ]
