# Generated by Django 5.2.9 on 2026-01-31 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0014_merge_20260131_1049'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthensPlatformSettings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(default='Athens Sustainability Platform', max_length=100)),
                ('platform_url', models.URLField(default='https://sustainability.athenas.co.in')),
                ('support_email', models.EmailField(default='support@athenas.co.in', max_length=254)),
                ('session_timeout_minutes', models.IntegerField(default=60)),
                ('require_mfa', models.BooleanField(default=True)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('password_expiry_days', models.IntegerField(default=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Athens Platform Settings',
                'verbose_name_plural': 'Athens Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='AthensAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('tenant_created', 'Tenant Created'), ('tenant_updated', 'Tenant Updated'), ('tenant_suspended', 'Tenant Suspended'), ('tenant_reactivated', 'Tenant Reactivated'), ('tenant_synced', 'Tenant Synced'), ('modules_updated', 'Modules Updated'), ('master_created', 'Master Created'), ('master_updated', 'Master Updated'), ('master_deleted', 'Master Deleted'), ('subscription_updated', 'Subscription Updated'), ('settings_updated', 'Settings Updated')], max_length=30)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Athens Audit Log',
                'verbose_name_plural': 'Athens Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AthensSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], default='trial', max_length=20)),
                ('seats', models.IntegerField(default=5)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('payment_provider', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athens_subscription', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Athens Subscription',
                'verbose_name_plural': 'Athens Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='AthensTenantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_modules', models.JSONField(default=list, help_text='List of enabled sustainability modules')),
                ('enabled_menus', models.JSONField(default=list, help_text='List of enabled menu items')),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athens_tenant', to='authentication.company')),
                ('master_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Athens Tenant Link',
                'verbose_name_plural': 'Athens Tenant Links',
            },
        ),
        migrations.CreateModel(
            name='AthensModuleSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('plan_tier', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athens_module_subscriptions', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Athens Module Subscription',
                'verbose_name_plural': 'Athens Module Subscriptions',
                'unique_together': {('company', 'module_code')},
            },
        ),
    ]
