# Generated by Django 5.2.9 on 2026-03-04 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('error_type', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
                ('file_path', models.CharField(max_length=500)),
                ('line_number', models.IntegerField(null=True)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orchestrator_error_pattern',
                'indexes': [models.Index(fields=['-last_seen'], name='orchestrato_last_se_5bc530_idx')],
            },
        ),
        migrations.CreateModel(
            name='AmazonQHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('context', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('error_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orchestrator.errorpattern')),
            ],
            options={
                'db_table': 'orchestrator_amazonq_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FixMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_description', models.TextField()),
                ('code_changes', models.JSONField()),
                ('status', models.CharField(choices=[('attempted', 'Attempted'), ('working', 'Working'), ('failed', 'Failed')], default='attempted', max_length=20)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('error_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_methods', to='orchestrator.errorpattern')),
            ],
            options={
                'db_table': 'orchestrator_fix_method',
                'ordering': ['-confidence_score', '-success_count'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('error_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.errorpattern')),
                ('fix_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orchestrator.fixmethod')),
            ],
            options={
                'db_table': 'orchestrator_workflow_error',
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.CharField(db_index=True, max_length=100)),
                ('workflow_name', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('context_data', models.JSONField(default=dict)),
                ('errors_encountered', models.ManyToManyField(through='orchestrator.WorkflowError', to='orchestrator.errorpattern')),
            ],
            options={
                'db_table': 'orchestrator_workflow_execution',
            },
        ),
        migrations.AddField(
            model_name='workflowerror',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.workflowexecution'),
        ),
    ]
